import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {build} from 'esbuild';import {createService} from '../functions/workspaces-core.mjs';import {createCommerce} from '../functions/commerce-core.mjs';
const require=createRequire(import.meta.url),{chromium}=require('/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules/playwright');
const root=path.resolve(import.meta.dirname,'../..'),site=path.join(root,'sites/doingchurch');
const compiled=await build({entryPoints:[path.join(root,'platform/client.mjs')],bundle:true,write:false,platform:'browser',external:['./pdf-proof.js'],format:'esm',alias:{'@netlify/identity':path.join(root,'platform/tests/identity-stub.mjs')}});
class Memory{rows=new Map();n=0;async get(k){return structuredClone(this.rows.get(k)?.data||null)}async list({prefix}){return {blobs:[...this.rows.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}}async getWithMetadata(k){return structuredClone(this.rows.get(k)||null)}async setJSON(k,data,options){const row=this.rows.get(k);if(options.onlyIfNew&&row||options.onlyIfMatch&&row?.etag!==options.onlyIfMatch)return{modified:false};const etag=String(++this.n);this.rows.set(k,{data:structuredClone(data),etag});return{modified:true,etag}}}
const api=createService(new Memory()),commerce=createCommerce({},new Memory()),owner={id:'qa-owner',name:'QA Owner',email:'qa@example.test'};
const server=http.createServer(async(req,res)=>{try{if(['/.netlify/functions/platform','/.netlify/functions/commerce'].includes(req.url)){let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);try{const result=await (req.url.endsWith('commerce')?commerce:api)(body.action,body,owner);res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(result))}catch(e){res.writeHead(e.status||500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}))}return}const u=new URL(req.url,'http://localhost'),p=path.join(site,u.pathname.endsWith('/')?u.pathname+'index.html':u.pathname);if(!p.startsWith(site)){res.writeHead(403);res.end();return}const data=u.pathname==='/workspace/client.js'?compiled.outputFiles[0].contents:fs.readFileSync(p);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':'application/octet-stream');res.end(data)}catch(e){res.writeHead(404);res.end('Not found')}});await new Promise(r=>server.listen(8767,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8767/workspace/');await page.getByLabel('Workspace name').fill('Our church QA');await page.getByRole('button',{name:'Create workspace'}).click();await page.getByRole('heading',{name:'Your people. Your next chapter.'}).waitFor();const base=page.url().split('#')[0];
 await page.goto(base+'#/new/church');await page.getByLabel('Mission',{exact:true}).fill('Love our neighbors');await page.getByLabel('Desired change').fill('Build friendship');await page.getByRole('button',{name:'Save document'}).click();await page.getByText('Saved to your shared workspace.').waitFor();
 await page.goto(base+'#/new/campaign');await page.locator('#profile-picker').selectOption({index:1});assert.equal(await page.getByLabel('Desired change').inputValue(),'Build friendship');await page.getByLabel('Start date',{exact:true}).fill('2026-10-04');await page.locator('select[name=days]').selectOption('30');assert.equal(await page.getByLabel('Number of gatherings').inputValue(),'4');await page.getByLabel('Who can see this document?').selectOption('workspace');await page.getByRole('button',{name:'Save document'}).click();await page.getByText('Saved to your shared workspace.').waitFor();await page.reload();await page.getByRole('button',{name:'Preview / export current draft'}).click();await page.getByText('30 days · 4 intentional gatherings').waitFor();await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Review a shareable snapshot'}).click();await page.getByRole('button',{name:'Create read-only link for this snapshot'}).click();await page.getByRole('heading',{name:'Your read-only snapshot'}).waitFor();const shared=await page.locator('#copy-link').inputValue();await page.getByRole('button',{name:'Close dialog'}).click();assert(shared.includes('#/shared/'));
 await page.goto(base+'#/new/service');await page.getByLabel('Start time',{exact:true}).fill('09:00');await page.getByLabel('Run sheet:').fill('5 | Welcome | Host\n20 | Worship | Team\n30 | Teaching | Pastor');await page.getByRole('button',{name:'Preview / export current draft'}).click();await page.getByRole('cell',{name:'09:25',exact:true}).waitFor();await page.getByRole('button',{name:'Close dialog'}).click();
 await page.goto(base+'#/people');await page.getByLabel('Invitee email').fill('friend@example.test');await page.getByRole('button',{name:'Create invitation link'}).click();await page.getByRole('heading',{name:'Your invitation is ready.'}).waitFor();await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'Revoke',exact:true}).first().click();await page.getByText('Link revoked.').waitFor();
 await page.goto(base+'#/reading-new');await page.getByLabel('Edition title',{exact:true}).fill('QA daily edition');await page.locator('select[name=days]').selectOption('7');await page.getByRole('button',{name:'Create reading edition'}).click();await page.getByLabel('Day title',{exact:true}).fill('A place to begin');await page.getByLabel('Scripture reference',{exact:true}).fill('John 15:1–5');await page.getByLabel('Complete daily reading').fill('A complete test reading for the participant experience.');await page.getByRole('button',{name:'Save this reading'}).click();await page.getByText('Reading saved.').waitFor();await page.getByRole('link',{name:'Open the reader'}).click();await page.getByLabel('Your private reflection').fill('Private QA reflection');await page.getByRole('button',{name:'Save private reflection'}).click();await page.getByText('Reflection saved privately.').waitFor();await page.getByRole('button',{name:'Mark day complete',exact:true}).click();await page.getByRole('button',{name:'Mark incomplete',exact:true}).waitFor();await page.reload();assert.equal(await page.getByLabel('Your private reflection').inputValue(),'Private QA reflection');await page.getByRole('button',{name:'Mark incomplete',exact:true}).waitFor();
 await page.goto(base+'#/store');await page.getByRole('heading',{name:'Checkout is not available yet.'}).waitFor();
 await page.setViewportSize({width:390,height:844});for(const route of ['','library/profiles','new/mission','people','reports','reader','store']){await page.goto(base+'#/'+route);await page.locator('#workspace-main h1').waitFor();const m=await page.evaluate(()=>({w:innerWidth,doc:document.documentElement.scrollWidth}));assert(m.doc<=m.w+1,route+' overflow');}
 await page.screenshot({path:'/private/tmp/workspace-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS shared workspace: create, save/reload, profile reuse, schedules, snapshot links, invitations/revoke and mobile routes.');
}finally{await browser.close();server.close()}
