import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {configuration,createCommerce,verifyWebhook,receiveOrder} from '../functions/commerce-core.mjs';
const env={SHOPIFY_STORE_DOMAIN:'example.myshopify.com',SHOPIFY_STOREFRONT_TOKEN:'test-token',SHOPIFY_WEBHOOK_SECRET:'test-secret',LT_APPROVED_PRODUCTS:JSON.stringify([{id:'campaign',title:'Test license',approved:true,variantId:'gid://shopify/ProductVariant/123',amount:'29.00',currency:'USD',license:'One church pilot'}])};
class Memory{rows=new Map();n=0;async get(k){return structuredClone(this.rows.get(k)?.data||null)}async getWithMetadata(k){return structuredClone(this.rows.get(k)||null)}async setJSON(k,data,o={}){const row=this.rows.get(k);if(o.onlyIfNew&&row||o.onlyIfMatch&&row?.etag!==o.onlyIfMatch)return{modified:false};this.rows.set(k,{data:structuredClone(data),etag:String(++this.n)});return{modified:true,etag:String(this.n)}}async list({prefix}){return{blobs:[...this.rows.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}}}
test('checkout stays off without approved configuration',async()=>{assert.equal(configuration({}).configured,false);const api=createCommerce({},new Memory());assert.equal((await api('offers',{},null)).configured,false);await assert.rejects(api('checkout',{product:'campaign'},{id:'a'}),{status:503});assert(!configuration({...env,LT_APPROVED_PRODUCTS:'[{"approved":false}]'}).configured)});
test('server verifies price, issues account-bound checkout and verifies paid order before receipts',async()=>{const store=new Memory(),requests=[];const api=createCommerce(env,store,async(url,args)=>{const req=JSON.parse(args.body);requests.push(req);return{ok:true,json:async()=>req.query.startsWith('query')?{data:{node:{availableForSale:true,price:{amount:'29.0',currencyCode:'USD'}}}}:{data:{cartCreate:{cart:{id:'cart',checkoutUrl:'https://example.myshopify.com/checkouts/test',cost:{totalAmount:{amount:'29.00',currencyCode:'USD'}}},userErrors:[]}}}}});const user={id:'alice',email:'alice@example.test'};const result=await api('checkout',{product:'campaign'},user);assert(result.checkoutUrl.startsWith('https:'));const key=requests[1].variables.input.attributes[0].value;assert.equal(requests[1].variables.input.buyerIdentity.email,user.email);
 const order={id:42,name:'#1042',note_attributes:[{name:'lt_checkout',value:key}],financial_status:'paid',currency:'USD',line_items:[{variant_id:123,quantity:1}],total_price:'29.00',updated_at:'2026-09-14T10:00:00Z',created_at:'2026-09-14T10:00:00Z'},raw=JSON.stringify(order),headers=new Headers({'x-shopify-topic':'orders/paid','x-shopify-shop-domain':env.SHOPIFY_STORE_DOMAIN,'x-shopify-hmac-sha256':createHmac('sha256',env.SHOPIFY_WEBHOOK_SECRET).update(raw).digest('base64')});assert(verifyWebhook(raw,headers.get('x-shopify-hmac-sha256'),env.SHOPIFY_WEBHOOK_SECRET));assert(!verifyWebhook(raw+'x',headers.get('x-shopify-hmac-sha256'),env.SHOPIFY_WEBHOOK_SECRET));await receiveOrder(raw,headers,env,store);assert((await receiveOrder(raw,headers,env,store)).duplicate);assert.equal((await api('receipts',{},user)).receipts.length,1);assert.equal((await api('receipts',{},{id:'bob'})).receipts.length,0);
 const wrong=JSON.stringify({...order,line_items:[{variant_id:999,quantity:1}]}),badHeaders=new Headers(headers);badHeaders.set('x-shopify-hmac-sha256',createHmac('sha256',env.SHOPIFY_WEBHOOK_SECRET).update(wrong).digest('base64'));await assert.rejects(receiveOrder(wrong,badHeaders,env,store),{status:400});
});
test('changed merchant price blocks checkout',async()=>{const api=createCommerce(env,new Memory(),async()=>({ok:true,json:async()=>({data:{node:{availableForSale:true,price:{amount:'99.00',currencyCode:'USD'}}}})}));await assert.rejects(api('checkout',{product:'campaign'},{id:'alice'}),{status:409})});
