import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {createPrintCheckout,signedWebhook,checkoutReady,sameAddress} from '../functions/print-checkout-core.mjs';
function fixture(){
 const map=new Map();let version=0,prints=0,drafts=0,cost='12.00',failPrint=false;
 const store={async get(k){return structuredClone(map.get(k)?.data??null)},async getWithMetadata(k){return structuredClone(map.get(k)??null)},async setJSON(k,data,opts={}){const old=map.get(k);if(opts.onlyIfNew&&old||opts.onlyIfMatch&&old?.etag!==opts.onlyIfMatch)return {modified:false};map.set(k,{data:structuredClone(data),etag:String(++version)});return {modified:true};},async list({prefix}){return {blobs:[...map.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}}};
 const env={LULU_API_ENVIRONMENT:'production',LULU_CLIENT_KEY:'test',LULU_CLIENT_SECRET:'test',LULU_CONTACT_EMAIL:'team@example.com',LT_PRINT_CHECKOUT_ENABLED:'true',SHOPIFY_STORE_DOMAIN:'example.myshopify.com',SHOPIFY_ADMIN_ACCESS_TOKEN:'test',SHOPIFY_WEBHOOK_SECRET:'test'};
 const owner='owner-a',address={name:'Test Person',street1:'100 Main St',street2:'',city:'Irvine',state_code:'CA',postcode:'92602',country_code:'US',phone_number:'+19495550100'};
 const body={interior_id:'inside',cover_id:'cover',pod_package_id:'0600X0900.BW.STD.PB.060UW444.MXX',contact_email:'test@example.com',expected_total:'12.00',currency:'USD',shipping_option:'GROUND_HD',shipping_address:address,line_item:{title:'Family Legacy',quantity:1}};
 const lulu=async(path,opts)=>{if(path.startsWith('/validate-'))return {id:'v1',status:'NORMALIZED'};if(path==='/print-job-cost-calculations/')return {total_cost_incl_tax:cost,currency:'USD'};if(path==='/print-jobs/'){prints++;if(failPrint)throw Error('connection lost');assert.equal(opts.body.line_items[0].title,'Family Legacy');return {id:345}};return {status:{name:'SHIPPED'},line_items:[{tracking_urls:['https://carrier.example/123','javascript:bad']}]};};
 const shopify=async(query,{input})=>{if(query.startsWith('query'))return {draftOrder:{order:{id:'gid://shopify/Order/100'}}};drafts++;assert.equal(input.lineItems[0].originalUnitPriceWithCurrency.amount,'12.00');return {draftOrderCreate:{draftOrder:{id:'gid://shopify/DraftOrder/1',invoiceUrl:'https://example.myshopify.com/invoice/abc',totalPriceSet:{presentmentMoney:{amount:'13.00',currencyCode:'USD'}}},userErrors:[]}}};
 const service=createPrintCheckout({env,store,lulu,shopify});
 const setup=async()=>{for(const [id,kind,count]of [['inside','interior',237],['cover','cover',1]])await store.setJSON('files-meta/'+id,{id,kind,owner,pageCount:count,url:'https://files.example/'+id+'.pdf',expiresAt:Date.now()+90*86400000});};
 const paid=id=>({id:100,name:'#100',financial_status:'paid',currency:'USD',total_price:'13.00',note_attributes:[{name:'lt_print_order',value:id}],line_items:[{sku:'LT-PRINT-'+id,quantity:1}],shipping_address:{address1:address.street1,address2:'',city:address.city,province_code:'CA',zip:'92602',country_code:'US'}});
 return {service,store,env,body,owner,setup,paid,get prints(){return prints},get drafts(){return drafts},set cost(v){cost=v},set failPrint(v){failPrint=v}};
}
test('webhook signatures reject tampering and missing secrets',()=>{const raw='{"id":1}',sig=createHmac('sha256','secret').update(raw).digest('base64');assert(signedWebhook(raw,sig,'secret'));assert(!signedWebhook(raw+' ',sig,'secret'));assert(!signedWebhook(raw,sig,''));});
test('checkout is gated by production, credentials and explicit enablement',()=>{const f=fixture();assert(checkoutReady(f.env));for(const key of ['LULU_CLIENT_SECRET','SHOPIFY_ADMIN_ACCESS_TOKEN','SHOPIFY_WEBHOOK_SECRET','LT_PRINT_CHECKOUT_ENABLED'])assert(!checkoutReady({...f.env,[key]:''}));assert(!checkoutReady({...f.env,LULU_API_ENVIRONMENT:'sandbox'}));});
test('file ownership is checked before quoting or creating checkout',async()=>{const f=fixture();await f.setup();await assert.rejects(f.service.checkout(f.body,'someone-else'));assert.equal(f.drafts,0);assert.equal(f.prints,0);});
test('stale or tampered quote cannot determine checkout price',async()=>{const f=fixture();await f.setup();await assert.rejects(f.service.checkout({...f.body,expected_total:'0.01'},f.owner),/price changed/);assert.equal(f.drafts,0);});
test('exact request reuses unpaid checkout without a second draft',async()=>{const f=fixture();await f.setup();const a=await f.service.checkout(f.body,f.owner),b=await f.service.checkout(f.body,f.owner);assert.equal(a.id,b.id);assert.equal(a.amount,1300);assert.equal(f.drafts,1);assert.equal(f.prints,0);});
test('verified paid callback creates exactly one Lulu job, including concurrent retries',async()=>{const f=fixture();await f.setup();const o=await f.service.checkout(f.body,f.owner);await Promise.all([f.service.paid(f.paid(o.id)),f.service.paid(f.paid(o.id))]);assert.equal(f.prints,1);assert.equal((await f.service.orders(f.owner))[0].luluId,'345');});
test('underpayment, currency mismatch, test payments and cancelled payments do not print',async()=>{for(const bad of [{total_price:'1.00'},{currency:'CAD'},{test:true},{cancelled_at:'today'},{financial_status:'pending'}]){const f=fixture();await f.setup();const o=await f.service.checkout(f.body,f.owner);await assert.rejects(f.service.paid({...f.paid(o.id),...bad}));assert.equal(f.prints,0);}});
test('changed address and increased provider cost hold paid orders for review',async()=>{for(const changed of ['address','price']){const f=fixture();await f.setup();const o=await f.service.checkout(f.body,f.owner),paid=f.paid(o.id);if(changed==='address')paid.shipping_address.zip='90210';else f.cost='99.00';assert.deepEqual(await f.service.paid(paid),{held:true});assert.equal(f.prints,0);assert.equal((await f.service.orders(f.owner))[0].status,'paid_needs_review');}});
test('uncertain printer submission is not retried and does not claim successful printing',async()=>{const f=fixture();await f.setup();const o=await f.service.checkout(f.body,f.owner);f.failPrint=true;await f.service.paid(f.paid(o.id));await f.service.paid(f.paid(o.id));assert.equal(f.prints,1);assert.equal((await f.service.orders(f.owner))[0].status,'fulfillment_needs_review');});
test('order status is owner-scoped and tracking URLs are filtered',async()=>{const f=fixture();await f.setup();const o=await f.service.checkout(f.body,f.owner);await f.service.paid(f.paid(o.id));await assert.rejects(f.service.status(o.id,'stranger'));const status=await f.service.status(o.id,f.owner);assert.equal(status.status,'SHIPPED');assert.deepEqual(status.tracking,['https://carrier.example/123']);assert(!JSON.stringify(status).includes('100 Main St'));});

test('files that expire after payment preparation are held rather than sent to Lulu',async()=>{const f=fixture();await f.setup();const o=await f.service.checkout(f.body,f.owner);const inside=await f.store.get('files-meta/inside');await f.store.setJSON('files-meta/inside',{...inside,expiresAt:Date.now()});await f.service.paid(f.paid(o.id));assert.equal(f.prints,0);assert.equal((await f.service.orders(f.owner))[0].status,'fulfillment_needs_review');});

test('payment comparison uses the customer currency rather than the shop base currency',async()=>{const f=fixture();await f.setup();const o=await f.service.checkout(f.body,f.owner);await f.service.paid({...f.paid(o.id),currency:'CAD',presentment_currency:'USD',total_price:'17.00',total_price_set:{presentment_money:{amount:'13.00',currency_code:'USD'}}});assert.equal(f.prints,1);});
