import test from 'node:test';
import assert from 'node:assert/strict';
import {createStaffProof,staffAccess} from '../functions/print-staff.mjs';
function fixture(){
 const rows=new Map(),owner='a'.repeat(64);let calls=0,price='12.00',fail=false;
 const env={LULU_STAFF_SESSION_HASH:owner,LULU_STAFF_ACCESS_EXPIRES:new Date(Date.now()+3600000).toISOString(),LULU_STAFF_PROOFS_ENABLED:'true',LULU_API_ENVIRONMENT:'production',LULU_CLIENT_KEY:'fixture',LULU_CLIENT_SECRET:'fixture',LULU_CONTACT_EMAIL:'team@example.com'};
 const store={async get(k){return structuredClone(rows.get(k)||null)},async setJSON(k,v,o={}){if(o.onlyIfNew&&rows.has(k))return {modified:false};rows.set(k,structuredClone(v));return {modified:true}}};
 const lulu=async(p)=>{if(p==='/print-job-cost-calculations/')return {currency:'USD',total_cost_incl_tax:price};calls++;if(fail)throw Error('Unknown submission result');return {id:123}};
 const service={async validate(){return {valid:true,files:[{url:'https://files.example/interior.pdf'},{url:'https://files.example/cover.pdf'}],pages:237,format:'0600X0900BWSTDPB060UW444MXX'}}};
 const staff=createStaffProof({env,store,lulu,service});
 const body={pod_package_id:'0600X0900BWSTDPB060UW444MXX',expected_total:'12.00',currency:'USD',shipping_option:'GROUND_HD',contact_email:'test@example.com',line_item:{title:'Family Legacy',quantity:1},shipping_address:{name:'Test Person',street1:'100 Main St',city:'Irvine',state_code:'CA',postcode:'92602',country_code:'US',phone_number:'+19495550100'}};
 return {staff,env,body,owner,service,get calls(){return calls},set price(v){price=v},set fail(v){fail=v}};
}
test('staff access rejects anonymous, wrong browser, missing and expired grants',()=>{const f=fixture();assert(staffAccess(f.env,f.owner));for(const o of ['',null,'b'.repeat(64)])assert(!staffAccess(f.env,o));assert(!staffAccess({...f.env,LULU_STAFF_ACCESS_EXPIRES:'invalid'},f.owner));assert(!staffAccess({...f.env,LULU_STAFF_ACCESS_EXPIRES:new Date(0).toISOString()},f.owner));assert(!staffAccess({...f.env,LULU_STAFF_ACCESS_EXPIRES:new Date(Date.now()+172800000).toISOString()},f.owner));});
test('staff ordering requires production credentials and explicit enablement',async()=>{for(const field of ['LULU_CLIENT_SECRET','LULU_STAFF_PROOFS_ENABLED','LULU_API_ENVIRONMENT']){const f=fixture();f.env[field]='';await assert.rejects(f.staff.prepare(f.body,f.owner));assert.equal(f.calls,0)}});
test('staff proof is limited to one copy, USD, validated PDFs and at most $100',async()=>{for(const bad of ['quantity','currency','price','files']){const f=fixture();if(bad==='quantity')f.body.line_item.quantity=2;if(bad==='currency')f.body.currency='CAD';if(bad==='price')f.price='100.01';if(bad==='files')f.service.validate=async()=>({valid:false});await assert.rejects(f.staff.prepare(f.body,f.owner));assert.equal(f.calls,0)}});
test('review preparation does not print, and requires explicit charge confirmation',async()=>{const f=fixture(),o=await f.staff.prepare(f.body,f.owner);assert.equal(f.calls,0);assert.equal(o.amount,1200);await assert.rejects(f.staff.submit({id:o.id,confirmed_total:12},f.owner));await assert.rejects(f.staff.submit({id:o.id,confirm:true,confirmed_total:1},f.owner));await assert.rejects(f.staff.submit({id:o.id,confirm:true,confirmed_total:12},'b'.repeat(64)));assert.equal(f.calls,0);});
test('concurrent submissions print only once with no Shopify configuration or calls',async()=>{const f=fixture(),o=await f.staff.prepare(f.body,f.owner),b={id:o.id,confirm:true,confirmed_total:12};await Promise.all([f.staff.submit(b,f.owner),f.staff.submit(b,f.owner)]);assert.equal(f.calls,1);assert.equal((await f.staff.submit(b,f.owner)).luluId,'123');});
test('increased quote does not consume authorization or send an order',async()=>{const f=fixture(),o=await f.staff.prepare(f.body,f.owner);f.price='13.00';await assert.rejects(f.staff.submit({id:o.id,confirm:true,confirmed_total:12},f.owner),/price increased/);assert.equal(f.calls,0);});
test('an uncertain printer result blocks any second submission under the same grant',async()=>{const f=fixture(),o=await f.staff.prepare(f.body,f.owner);f.fail=true;const result=await f.staff.submit({id:o.id,confirm:true,confirmed_total:12},f.owner);assert.equal(result.status,'fulfillment_needs_review');const second=await f.staff.prepare(f.body,f.owner);await assert.rejects(f.staff.submit({id:second.id,confirm:true,confirmed_total:12},f.owner),/already been used/);assert.equal(f.calls,1);});
