// Local-only seeded test server. No real accounts, provider calls, uploads or messages.
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {build} from 'esbuild';import {createService} from '../functions/workspaces-core.mjs';import {inspectPDF} from '../pdf-inspection.mjs';
const root=path.resolve(import.meta.dirname,'../..'),site=path.join(root,'sites/doingchurch');
const compiled=await build({entryPoints:[path.join(root,'platform/client.mjs')],bundle:true,write:false,platform:'browser',external:['./pdf-proof.js','./pdf-viewer.js','./brand-assets.js'],format:'esm',alias:{'@netlify/identity':path.join(root,'platform/tests/identity-stub.mjs')}});
class Memory{rows=new Map();n=0;async getWithMetadata(k){return structuredClone(this.rows.get(k)||null)}async setJSON(k,data,options){const row=this.rows.get(k);if(options.onlyIfNew&&row||options.onlyIfMatch&&row?.etag!==options.onlyIfMatch)return{modified:false};const etag=String(++this.n);this.rows.set(k,{data:structuredClone(data),etag});return{modified:true,etag}}}
const api=createService(new Memory()),owner={id:'qa-owner',name:'QA Owner',email:'qa@example.test'};let w=await api('create',{name:'Studio QA Church',kind:'church'},owner);for(const document of [{type:'source',title:'A welcome at the table',visibility:'workspace',content:{recipe:'source',transcript:'Jesus invites us to love our neighbor. Read Luke 10:25–37. Make room at your table and practice hospitality this week.',author:'QA Pastor',scripture:'Luke 10:25–37'}},{type:'edition',title:'A three-day welcome',visibility:'workspace',content:{recipe:'reader',status:'Draft',days:[1,2,3].map(day=>({day,title:'Day '+day,scripture:'Luke 10:25–37',body:'Make room for a neighbor today.',practice:'Share a meal.'}))}}])w=await api('save',{workspace:w.workspace.id,etag:w.etag,document},owner);
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1:8769');if(url.pathname.startsWith('/.netlify/functions/')){let raw='';for await(const chunk of req)raw+=chunk;const b=JSON.parse(raw||'{}');let result={};try{if(url.pathname.endsWith('/platform'))result=await api(b.action,b,owner);else if(url.pathname.endsWith('/studio'))result={transcription:false,writing:false,email:false,sms:false,deliveryEnabled:false};else if(url.pathname.endsWith('/delivery'))result={campaigns:[],counts:{email:0,sms:0},preferences:{emailOptIn:false,smsOptIn:false,phone:''},admin:true,ready:{email:false,sms:false,smsVerification:false},enabled:false};else if(url.pathname.endsWith('/print-files')){if(b.action==='list')result={files:[]};else{const report=await inspectPDF(Buffer.from(b.pdf,'base64'),{kind:b.kind});result={file:{pageCount:report.pageCount,dimensions:report.dimensions},url:'https://example.test/qa-'+b.kind+'.pdf'};}}else if(url.pathname.endsWith('/lulu')){const action=url.searchParams.get('action');if(action==='health'||action==='connection')result={configured:true,authenticated:true,environment:'sandbox',orders_enabled:false};if(action==='shipping-options')result=[{level:'GROUND',cost_excl_tax:'10.00'},{level:'EXPRESS',cost_excl_tax:'25.00'}];if(action==='quote')result={currency:'USD',total_cost_incl_tax:String(b.line_item.quantity*5+12),total_tax:'2.00',line_item_costs:[{total_cost_excl_tax:b.line_item.quantity*5}],shipping_cost:{total_cost_excl_tax:'10.00'},fulfillment_cost:{total_cost_excl_tax:0}};}res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(result));}catch(e){res.writeHead(e.status||400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));}return;}
 const base=url.pathname.startsWith('/workspace/')||url.pathname.startsWith('/fonts/')?site:path.join(root,'dist'),p=path.resolve(base,'.'+url.pathname+(url.pathname.endsWith('/')?'index.html':''));if(!p.startsWith(base+path.sep))throw Error('Bad path');const data=url.pathname==='/workspace/client.js'?compiled.outputFiles[0].contents:fs.readFileSync(p);res.setHeader('Content-Type',/\.(js|mjs)$/.test(p)?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':p.endsWith('.pdf')?'application/pdf':'application/octet-stream');res.end(data);
 }catch(e){res.writeHead(404);res.end('Not found');}});server.listen(8769,'127.0.0.1',()=>console.log('Seeded QA workspace: http://127.0.0.1:8769/workspace/#/dashboard'));
