site.name='40 Day Campaigns';site.domain='40DayCampaigns.com';
const design={accent:'#b62e16',soft:'#ffe697',ink:'#222724',mark:'40',wordmark:'40 Day Campaigns',tagline:'Move messages to movement.',library:'Find a campaign',builder:'Build my campaign',finderTitle:'Find the right<br>movement for now.',builderTitle:'Build the journey.<br>Move the church.'};
function campaignDoor(number,title,text,path,label,cls=''){return `<article class="campaign-door ${cls}"><span>${number}</span><h2>${title}</h2><p>${text}</p>${link(path,label+' '+icon('arrow'),cls==='featured'?'primary':'button')}</article>`}
function campaignDiscovery(){const groups=[
 ['BIBLE',[['Books','Romans'],['Passages','Psalm 23'],['Characters','David'],['Life of Christ','Jesus'],['Theology','Grace']]],
 ['LIFE NEEDS',[['Anxiety','anxiety'],['Marriage','marriage'],['Parenting','parenting'],['Finances','money'],['Purpose','purpose']]],
 ['CHURCH OUTCOMES',[['Prayer','prayer'],['Community','community'],['Generosity','generosity'],['Leadership','leadership'],['Mission','mission']]],
 ['SEASONS',[['New Year','new year'],['Lent','lent'],['Easter','easter'],['Fall Launch','fall'],['Advent','advent']]]
];return `<section class="campaign-discovery"><div class="section-head"><div><span class="eyebrow">MULTIPLE WAYS IN · ONE CONNECTED LIBRARY</span><h2>Start where pastors actually start.</h2></div><p>Search Scripture, felt need, ministry outcome, season, audience, or journey length. Every result keeps its source identity and production status visible.</p></div><div class="discovery-bands">${groups.map(([name,items])=>`<article><h3>${name}</h3><div>${items.map(([label,q])=>link('explore',label+' '+icon('arrow'),'',{q})).join('')}</div></article>`).join('')}</div><div class="journey-strip"><span>BUILD IT AS</span>${[7,10,21,30,40].map(n=>link('explore',n+' days','',{duration:n})).join('')}${link('explore','4–8 week series','',{type:'series'})}${link('build','Season builder')}</div></section>`}
function campaignSystem(){const outputs=['Weekend sermons','Small groups','Daily devotionals','Family conversations','Kids','Students','Leader training','Prayer','Stories','Email + text','Social content','Video briefs','Landing page','Design + print','Assessment','Next steps','Generosity initiative'];return `<section class="campaign-system"><div class="system-copy"><span class="eyebrow">FROM ONE MESSAGE TO A WHOLE-CHURCH JOURNEY</span><h2>Don’t stop at the sermon.</h2><p>Start with your sermon series, one message, a Bible book or passage, a character, felt need, church vision, ministry initiative, existing campaign, or a blank page. Then build only the pieces your church actually needs.</p><div class="actions">${link('build','Build my campaign '+icon('arrow'),'primary')}<a class="button" href="https://lifetogether-doing-church-together.netlify.app/workspace/#/new/source">Bring in my sermons →</a></div></div><div class="output-cloud">${outputs.map((x,i)=>`<span><b>${String(i+1).padStart(2,'0')}</b>${x}</span>`).join('')}</div></section>`}
function intelligenceStory(){return `<section class="campaign-intelligence"><div><span class="eyebrow">CAMPAIGN INTELLIGENCE</span><h2>The library gets useful when it knows your church.</h2><p>Bring together your pastor, theology, sermon history, people, ministries, formation priorities, survey results, vision, and what happened last time. Then use that context to compare possible next steps without replacing pastoral discernment.</p></div><div class="intelligence-flow"><span>PASTOR</span><i>+</i><span>CHURCH</span><i>+</i><span>PEOPLE</span><i>+</i><span>VISION</span><i>=</i><strong>BEST NEXT FAITHFUL STEP</strong></div><div class="actions">${link('choose','Help me decide '+icon('arrow'),'primary')}${link('intelligence','Explore Church Intelligence','button')}</div></section>`}
function ecosystem(){const items=[
 ['SermonCurator.com','Find and build the message.','https://lifetogether-sermon-curator.netlify.app/'],
 ['40DayCampaigns.com','Turn messages into movements.','#/home'],
 ['SmallGroupCurriculum.com','Move Sunday into community.','https://lifetogether-small-group-curriculum.netlify.app/'],
 ['Pastor’s Library','Multiply your pastor’s teaching.','https://lifetogether-doing-church-together.netlify.app/workspace/#/sermon-intake'],
 ['Church Intelligence™','Understand where your church is and what may come next.','#/intelligence'],
 ['Church Publishing','Move message to manuscript to ministry to print.','https://lifetogethermasterlibary.netlify.app/#/print-studio']
];return `<section class="campaign-ecosystem"><div class="section-head"><div><span class="eyebrow">THE LIFETOGETHER INTELLIGENCE ECOSYSTEM</span><h2>One engine. Every next step connected.</h2></div></div><div>${items.map(([title,text,url])=>`<a href="${url}"><strong>${title}</strong><span>${text}</span></a>`).join('')}</div></section>`}
function brandedHome(){return `<section class="campaign-poster"><div class="poster-top"><span>ONE CHURCH · ONE SHARED JOURNEY</span><span>${records.length.toLocaleString()} SOURCE-LINKED CONCEPTS</span></div><div class="poster-layout"><div class="poster-copy"><span class="eyebrow hero-kicker">40DAYCAMPAIGNS.COM</span><h1>Move messages<br><span>to movement.</span></h1><p>Find or build the right biblical journey for the moment your church is in—then connect Sunday, groups, daily life, families, leaders, and next steps around one shared direction.</p><div class="hero-actions">${link('explore','Find a campaign '+icon('arrow'),'primary')}${link('build','Build my own','button')}${link('choose','Help me decide','button')}</div><small>Find it. Build it. Make it yours. Move your church.</small></div><div class="forty-art" aria-hidden="true"><strong>40</strong><span>DAYS. EVERYBODY IN.</span><div>${Array.from({length:40},(_,i)=>`<i class="${i%7===0?'gather':''}"></i>`).join('')}</div><small>A little every day. Something greater together.</small></div></div></section><div class="campaign-ticker"><span>SUNDAY TEACHING</span><b>+</b><span>SMALL GROUPS</span><b>+</b><span>DAILY PRACTICE</span><b>+</b><span>FAMILIES</span><b>=</b><span>MOVEMENT</span></div><section class="campaign-doors">${campaignDoor('01','Find a campaign','Search the master library by Scripture, topic, felt need, outcome, season, audience, duration, and ministry.','explore','Explore the library')}${campaignDoor('02','Build a campaign','Begin with your sermons, a book, Scripture, church vision, ministry initiative, or an existing campaign.','build','Start building','featured')}${campaignDoor('03','Help me decide','Use Church Intelligence to compare three source-grounded pathways for this season.','choose','Find our next step')}</section>${campaignDiscovery()}${homeShelf('Campaigns worth exploring.','CURATED STARTING POINTS')}${campaignSystem()}${intelligenceStory()}${ecosystem()}${brandCTA('Day one is closer than you think.','Connect teaching, groups, daily devotionals, family experiences, leader preparation, assessments, and Day 41 in one production brief.','Build the movement')}`}