'use strict';
(async()=>{
const root=document.querySelector('#app'),toast=document.querySelector('#toast');
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const icon=name=>{const paths={search:'M10 3a7 7 0 1 0 0 14a7 7 0 0 0 0-14m5 12 6 6',arrow:'M4 12h16m-6-6 6 6-6 6',book:'M4 4h16v16H4zm5 0v16m4-12h4m-4 4h4',source:'M7 3H3v18h4m10-18h4v18h-4M14 7l-4 10',check:'m4 12 5 5L20 6',menu:'M4 7h16M4 12h16M4 17h16'};return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.arrow}"/></svg>`};
const bytes=Uint8Array.from(atob(window.LT_SITE_DATA.payload),c=>c.charCodeAt(0));
const data=JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text());
const site=data.site,records=data.records,byId=new Map(records.map(r=>[r.id,r]));
const themeLabels={community:'Belonging & community',formation:'Faith & formation',generosity:'Generosity & stewardship',legacy:'Family & legacy',leadership:'Purpose & leadership',peace:'Hope & resilience',mission:'Outreach & mission',scripture:'Life & teaching of Jesus'};
const typeLabels={campaign:'Campaign & journey',catalytic:'Catalytic Sunday',series:'Teaching series'};
document.documentElement.style.setProperty('--accent',site.accent);document.documentElement.style.setProperty('--soft',site.soft);document.documentElement.style.setProperty('--ink',site.ink);
let menu=false;
const params=()=>new URLSearchParams(location.hash.split('?')[1]||'');
const route=()=>{const path=(location.hash.replace(/^#\/?/,'').split('?')[0]||'home').split('/').map(decodeURIComponent);return path};
const href=(path,values={})=>{const p=new URLSearchParams();for(const [k,v] of Object.entries(values))if(v)p.set(k,v);return '#/'+path+(p.size?'?'+p:'')};
const link=(path,label,cls='',values={})=>`<a class="${cls}" href="${href(path,values)}">${label}</a>`;
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2800)}
function header(active){return `<header class="site-header"><a class="identity" href="#/home"><span class="monogram">${esc(site.name.split(/\s+/).map(x=>x[0]).slice(0,2).join(''))}</span><span><strong>${esc(site.name)}</strong><small>A LifeTogether ministry</small></span></a><button class="menu" aria-expanded="${menu}" aria-controls="site-nav">${icon('menu')} Menu</button><nav id="site-nav" class="${menu?'open':''}" aria-label="Main navigation">${[['home','Home'],['explore','Explore'],['about','Purpose']].map(([r,l])=>link(r,l,active===r?'active':'')).join('')}<a href="https://lifetogethermasterlibary.netlify.app/#/campaign-finder">Campaign builder ${icon('arrow')}</a></nav></header>`}
function network(){return `<footer><div><strong>${esc(site.name)}</strong><p>${esc(site.promise)}</p></div><div><span>THE LIFETOGETHER NETWORK</span><nav aria-label="LifeTogether network">${data.network.map(x=>`<a href="${esc(x.url)}">${esc(x.name)}</a>`).join('')}</nav></div><p>Every resource remains connected to its original title and source. Cataloged ideas may still require manuscript, rights, and edition review.</p></footer>`}
function frame(active,body){root.innerHTML=header(active)+`<main id="main">${body}</main>`+network();document.title=`${site.name} · LifeTogether`;menu=false;window.scrollTo(0,0)}
function controls(f={}){return `<form id="finder" class="finder" role="search"><label class="search"><span class="sr-only">${esc(site.prompt)}</span>${icon('search')}<input name="q" type="search" maxlength="180" value="${esc(f.q||'')}" placeholder="${esc(site.prompt)}"></label><button class="primary" type="submit">Find resources ${icon('arrow')}</button><div class="filters"><label>Formation goal<select name="goal"><option value="">Every goal</option>${Object.entries(themeLabels).map(([v,l])=>`<option value="${v}" ${f.goal===v?'selected':''}>${esc(l)}</option>`).join('')}</select></label><label>Duration in source<select name="duration"><option value="">Any length</option>${data.durations.map(n=>`<option value="${n}" ${String(f.duration)===String(n)?'selected':''}>${n} days</option>`).join('')}<option value="unknown" ${f.duration==='unknown'?'selected':''}>Length not stated</option></select></label><label>Resource type<select name="type"><option value="">Every type</option>${Object.entries(typeLabels).map(([v,l])=>`<option value="${v}" ${f.type===v?'selected':''}>${esc(l)}</option>`).join('')}</select></label><label>Order<select name="sort"><option value="">Best match</option><option value="title" ${f.sort==='title'?'selected':''}>Title A–Z</option></select></label></div></form>`}
function filtered(){const p=params(),q=(p.get('q')||'').toLowerCase().trim(),words=q.split(/\s+/).filter(Boolean),goal=p.get('goal'),duration=p.get('duration'),type=p.get('type');let out=records.filter(r=>(!words.length||words.every(w=>r.search.includes(w)))&&(!goal||r.goals.includes(goal))&&(!type||r.type===type)&&(!duration||(duration==='unknown'?!r.durations.length:r.durations.includes(Number(duration)))));return out.sort((a,b)=>p.get('sort')==='title'?a.title.localeCompare(b.title):b.score-a.score||a.title.localeCompare(b.title))}
function chips(){return `<div class="chips"><span>Begin with</span>${site.featured.map(type=>link('explore',typeLabels[type],'', {type})).join('')}${link('explore','40-day journeys','',{duration:40})}${link('explore','Length to discern','',{duration:'unknown'})}</div>`}
function card(r,i){const duration=r.durations.length?r.durations.join(' / ')+' days':'Length not stated',goal=r.goals[0]?themeLabels[r.goals[0]]:'Formation goal to discern';return `<article class="resource tone-${i%4}"><a class="cover" href="${href('resource/'+encodeURIComponent(r.id))}"><small>${esc(site.name)}</small><strong>${esc(r.title)}</strong><i>${String(i+1).padStart(2,'0')}</i></a><div class="resource-body"><span class="status">${esc(r.status)}</span><h2>${link('resource/'+encodeURIComponent(r.id),esc(r.title))}</h2><p>${esc(r.subtitle||'No subtitle was supplied in the source.')}</p><div class="meta"><span>${esc(duration)}</span><span>${esc(goal)}</span></div><div class="resource-foot">${link('resource/'+encodeURIComponent(r.id),'Explore '+icon('arrow'))}<small>${esc(r.id)}</small></div></div></article>`}
function results(limit=12){const list=filtered(),p=params(),page=Math.max(1,Number(p.get('p'))||1),pages=Math.max(1,Math.ceil(list.length/limit)),current=Math.min(page,pages),items=list.slice((current-1)*limit,current*limit),values=Object.fromEntries(p);return `<section class="results"><div class="section-head"><div><span class="eyebrow">SOURCE-LINKED STARTING POINTS</span><h2>${p.get('q')?`Results for “${esc(p.get('q'))}”`:'Ideas for your next season'}</h2><p role="status">${list.length.toLocaleString()} ${list.length===1?'resource':'resources'}${list.length?' · Showing '+((current-1)*limit+1)+'–'+Math.min(current*limit,list.length):''}</p></div>${p.size?link('explore','Clear filters','button'):''}</div>${items.length?`<div class="resource-grid">${items.map(card).join('')}</div><nav class="pager" aria-label="Results pages"><span>Page ${current} of ${pages}</span><div>${current>1?link('explore','Previous','button',{...values,p:current-1}):'<span></span>'}${current<pages?link('explore','Next '+icon('arrow'),'button',{...values,p:current+1}):''}</div></nav>`:`<div class="empty"><h2>Try a wider starting point.</h2><p>Remove one filter or search a broader theme. Lengths appear only when the source states a day count.</p>${link('explore','See all resources','primary')}</div>`}</section>`}
function home(){const featured=records.slice(0,6);frame('home',`<section class="hero"><div><span class="eyebrow">${esc(site.eyebrow)}</span><h1>${esc(site.headline)}</h1><p>${esc(site.description)}</p></div><aside><span>FOR</span><p>${esc(site.audience)}</p><strong>${esc(site.promise)}</strong></aside></section><section class="finder-wrap"><div class="section-head"><div><span class="eyebrow">START WITH THE NEED</span><h2>What are you hoping to help people become?</h2></div><p>Search the actual source library. Titles, subtitles, durations, and status remain attached.</p></div>${controls()}${chips()}</section><section class="home-resources"><div class="section-head"><div><span class="eyebrow">CURATED FOR THIS MINISTRY</span><h2>Places to begin</h2></div>${link('explore','Explore every match '+icon('arrow'))}</div><div class="resource-grid">${featured.map(card).join('')}</div></section><section class="path"><span class="eyebrow">A SIMPLE PATH FORWARD</span><div>${site.steps.map((s,i)=>`<article><b>0${i+1}</b><p>${esc(s)}</p></article>`).join('')}</div></section>`)}
function explore(){const p=params();frame('explore',`<section class="page-intro"><span class="eyebrow">${esc(site.name)} / RESOURCE FINDER</span><h1>Find the right starting point.</h1><p>Search the source-linked ideas selected for ${esc(site.audience.toLowerCase())}.</p></section>${controls(Object.fromEntries(p))}${chips()}${results()}`)}
function detail(id){const r=byId.get(id);if(!r){frame('explore',`<section class="empty page-empty"><h1>This resource is unavailable.</h1><p>It may have moved outside this ministry collection.</p>${link('explore','Return to the finder','primary')}</section>`);return}const duration=r.durations.length?r.durations.join(' / ')+' days':'Not stated in source',goals=r.goals.length?r.goals.map(x=>themeLabels[x]).join(' · '):'To discern';frame('explore',`<a class="back" href="#/explore">← Back to resources</a><section class="detail"><div class="detail-cover"><small>${esc(site.name)}</small><h1>${esc(r.title)}</h1><p>${esc(r.subtitle)}</p></div><div><span class="eyebrow">${esc(r.status)}</span><h1>${esc(r.title)}</h1><p class="subtitle">${esc(r.subtitle||'No subtitle was supplied in the source.')}</p><dl><div><dt>Source duration</dt><dd>${esc(duration)}</dd></div><div><dt>Formation direction</dt><dd>${esc(goals)}</dd></div><div><dt>Source format</dt><dd>${esc(r.format||typeLabels[r.type])}</dd></div><div><dt>Source identity</dt><dd>${esc(r.id)}</dd></div></dl><div class="source-note"><strong>Start with what the source establishes.</strong><p>This record preserves the original title, subtitle, format, and stated length. A catalog entry does not confirm that a complete manuscript or every audience edition exists.</p></div><div class="actions"><a class="primary" href="https://lifetogethermasterlibary.netlify.app/#/campaign-finder/${encodeURIComponent('catalog:'+r.id)}">Build from this idea ${icon('arrow')}</a><a class="button" href="https://lifetogethermasterlibary.netlify.app/#/record/${encodeURIComponent(r.id)}">Review original source</a></div></div></section>`)}
function about(){frame('about',`<section class="page-intro"><span class="eyebrow">WHY THIS MINISTRY EXISTS</span><h1>${esc(site.promise)}</h1><p>${esc(site.description)}</p></section><section class="about-grid"><article><span>01</span><h2>Who it serves</h2><p>${esc(site.audience)}</p></article><article><span>02</span><h2>How it helps</h2><ol>${site.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></article><article><span>03</span><h2>How sources are handled</h2><p>Original titles, subtitles, source IDs, and stated durations remain visible. Restricted and removed records are excluded from this site.</p></article></section><section class="network-story"><h2>One ministry within a larger formation network.</h2><p>LifeTogether connects sermon intelligence, campaign intelligence, curriculum, families, advisors, stewardship, flourishing, work, and church formation without erasing the identity of each source.</p>${link('explore','Explore this ministry’s resources '+icon('arrow'),'primary')}</section>`)}
document.addEventListener('click',e=>{const b=e.target.closest('.menu');if(b){menu=!menu;const nav=document.querySelector('#site-nav');nav.classList.toggle('open',menu);b.setAttribute('aria-expanded',menu)}else if(e.target.closest('a[href^="#/"]'))menu=false});
document.addEventListener('submit',e=>{if(e.target.id!=='finder')return;e.preventDefault();const f=Object.fromEntries(new FormData(e.target));location.hash=href('explore',f).slice(1)});
document.addEventListener('change',e=>{if(e.target.closest('#finder')&&e.target.tagName==='SELECT')e.target.form.requestSubmit()});
function render(){const r=route();if(r[0]==='home')home();else if(r[0]==='explore')explore();else if(r[0]==='resource')detail(decodeURIComponent(r[1]||''));else if(r[0]==='about')about();else{location.hash='/home'}}
window.addEventListener('hashchange',render);render();
})().catch(error=>{document.querySelector('#app').innerHTML=`<main class="empty page-empty"><h1>This library could not open.</h1><p>${String(error.message||error)}</p></main>`;console.error(error)});
