import {PDFDocument,rgb} from 'pdf-lib';import fontkit from '@pdf-lib/fontkit';
import {recipes} from './planning.mjs';
const paper=rgb(.969,.945,.91),ink=rgb(.18,.2,.17),accent=rgb(.61,.31,.22);
export async function createProof(doc,fontBytes){
 const pdf=await PDFDocument.create();pdf.registerFontkit({create:bytes=>{const f=fontkit.create(bytes);return f.variationAxes?.wght?f.getVariation({wght:400}):f}});const font=await pdf.embedFont(fontBytes,{subset:true});pdf.setTitle(doc.title);pdf.setSubject('LifeTogether working proof — editorial and print review required');pdf.setCreator('LifeTogether');
 const width=450,height=666,margin=54,usable=width-margin*2;let page,y;const pages=[],draws=[];
 function pageStart(){page=pdf.addPage([width,height]);page.drawRectangle({x:0,y:0,width,height,color:paper});y=height-58;pages.push({page:pages.length+1,lines:0});draws.push({page,items:[]});page.drawText('LIFETOGETHER · WORKING PROOF',{x:margin,y:height-28,font,size:7,color:accent});page.drawLine({start:{x:margin,y:36},end:{x:width-margin,y:36},thickness:.5,color:accent});page.drawText(String(pages.length),{x:width-margin-12,y:23,font,size:8,color:ink});}
 function wrapped(text,size){const lines=[];for(const paragraph of String(text||'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').split('\n')){let line='';for(let word of paragraph.split(/\s+/)){if(!word)continue;while(font.widthOfTextAtSize(word,size)>usable){let n=1;while(n<word.length&&font.widthOfTextAtSize(word.slice(0,n+1),size)<=usable)n++;if(line){lines.push(line);line=''}lines.push(word.slice(0,n));word=word.slice(n)}if(!word)continue;const next=line?line+' '+word:word;if(font.widthOfTextAtSize(next,size)>usable){lines.push(line);line=word}else line=next}if(line)lines.push(line);else if(!paragraph.trim())lines.push('')}return lines}
 function write(text,size=10.5,color=ink,space=10){const lines=wrapped(text,size),leading=size*1.55;for(let i=0;i<lines.length;i++){const line=lines[i];if(y-leading<54)pageStart();draws.at(-1).items.push({line,y,size,color,advance:leading+(i===lines.length-1?space:0)});if(line)pages.at(-1).lines++;y-=leading}y-=space;}
 function heading(text){if(y<120)pageStart();write(text,16,accent,8)}
 pageStart();y=height-150;write(doc.title,28,ink,22);write(doc.content.subtitle||'A LifeTogether working edition',13,accent,18);write('PROOF FOR REVIEW',9,accent);write('Review teaching, source permissions, page layout and every supplied file before commercial release or printing.',10.5,ink);write('Trim: 6 × 9 inches\nPDF: 6.25 × 9.25 inches, including 0.125-inch bleed on every edge.\nThis PDF is the interior only. The cover requires dimensions matched to the final page count and selected Lulu format.',9,ink);
 pageStart();
 if(doc.content.recipe==='reader'){heading('Edition notes');write('Status: '+doc.content.status+'\nScripture translation: '+doc.content.translation+'\nReviewer: '+(doc.content.reviewer||'Not recorded'));write(doc.content.sourceNotes||'Source and permission notes have not been supplied.');for(const r of doc.content.days){pageStart();heading('Day '+r.day+' · '+(r.title||'Title not supplied'));if(r.subtitle)write(r.subtitle,12,accent);write('Read: '+(r.scripture||'Reference not supplied'),9,accent);write(r.body||'READING NOT SUPPLIED — THIS DAY IS INCOMPLETE.');if(r.practice){heading('Put it into practice');write(r.practice)}if(r.questions){heading('Reflect');write(r.questions)}}
 }else{const recipe=recipes[doc.content.recipe];for(const f of recipe?.fields||[]){heading(f.label);write(doc.content[f.key]||'Not yet supplied.')}}
 const tail=draws.at(-1),previous=draws.at(-2);
 if(draws.length>2){while(tail.items.map(x=>x.line).join(' ').length<700&&previous.items.length>5){const item=previous.items.at(-1);if(tail.items.reduce((n,x)=>n+x.advance,0)+item.advance>height-120)break;tail.items.unshift(previous.items.pop())}let cursor=height-58;for(const item of tail.items){item.y=cursor;cursor-=item.advance}}
 for(let index=0;index<draws.length;index++){const {page:sheet,items}=draws[index];for(const item of items)if(item.line)sheet.drawText(item.line,{x:margin,y:item.y,font,size:item.size,color:item.color});const lastY=items.at(-1)?.y||height-58;pages[index].lines=items.filter(x=>x.line).length;pages[index].characters=items.map(x=>x.line).join(' ').length;pages[index].lastTextY=lastY;if(index>0&&lastY>170){sheet.drawText('PROOF REVIEW NOTES',{x:margin,y:lastY-40,font,size:7,color:accent});for(let rule=lastY-60;rule>57;rule-=24)sheet.drawLine({start:{x:margin,y:rule},end:{x:width-margin,y:rule},thickness:.3,color:rgb(.76,.69,.60)});pages[index].reviewNoteSpace=true}}
 const bytes=await pdf.save();const verified=await PDFDocument.load(bytes);if(verified.getPageCount()!==pages.length)throw Error('Proof page count mismatch.');return {bytes,manifest:{pageCount:pages.length,widthInches:6.25,heightInches:9.25,trimWidthInches:6,trimHeightInches:9,bleedInches:.125,embeddedFonts:true,reviewRequired:true,pages}};
}
