export const recipeGroups={
 profiles:{label:'People & purpose',intro:'Keep your mission, voice and context ready for every new journey.'},
 campaigns:{label:'Campaign studio',intro:'Bring your source, teaching, people and next steps into one plan.'},
 sunday:{label:'Sunday & seasons',intro:'Prepare the gathering and the journey that follows it.'},
 tools:{label:'Practical tools',intro:'Work through a useful conversation, save your decisions and return to them.'},
 sources:{label:'Sources & editions',intro:'Keep the original source, permission and review history attached.'},
 ministry:{label:'Ministry pathways',intro:'Give each next step an owner, a date and a way to follow through.'},
 advisors:{label:'Advisor relationships',intro:'Prepare a thoughtful engagement and keep the family in control of sharing.'}
};
const f=(key,label,type='textarea',options)=>({key,label,type,options});
const field=(key,label,options)=>f(key,label,'select',options);
const baseProfile=[f('mission','Mission'),f('values','Values'),f('context','People, strengths and challenges'),f('goals','Desired change'),f('history','Recent journeys and lessons learned')];
const roles=['Not started','In progress','Ready for review','Complete'];
export const recipes={
 church:{group:'profiles',type:'profile',title:'Church & pastor intelligence',fields:[...baseProfile,f('pastor','Pastor / teaching team','text'),f('theology','Theological convictions to preserve'),f('voice','Voice, tone and expressions'),f('translation','Preferred Scripture translation','text'),f('sermonHistory','Sermon series and recurring themes'),f('congregation','Congregation and age groups'),f('reviewer','Teaching reviewer','text')]},
 family:{group:'profiles',type:'profile',title:'Family intelligence',fields:[...baseProfile,f('generations','Generations taking part'),f('traditions','Stories and traditions'),f('boundaries','Topics and details to keep private')]},
 team:{group:'profiles',type:'profile',title:'Workplace intelligence',fields:[...baseProfile,f('culture','Culture and leadership needs'),f('participation','How participation stays voluntary'),f('language','Appropriate faith language and setting')]},
 campaign:{group:'campaigns',type:'campaign',title:'Campaign plan',fields:[f('subtitle','Subtitle','text'),field('mode','Setting',['Churchwide','Small group','Ministry class / ABF','Family','Workplace']),field('customization','Starting point',['Ready-made','Personalize','Build from sermons']),field('days','Days',['7','10','21','30','40','60','90']),f('sessions','Number of gatherings','number'),f('start','Start date','date'),f('goal','Desired change'),f('bigIdea','One central idea'),f('scripture','Scripture passages and translation'),f('sourceIds','Source IDs / URLs and permission references'),f('profileNotes','Which profile details should shape this plan?'),f('weekly','Weekly titles, subtitles and teaching direction'),f('daily','Daily titles, subtitles and practices'),f('leader','Leader preparation and coaching'),f('editionPlan','Audience editions actually needed'),f('communications','Launch, invitation and follow-up messages'),f('continuation','After the last day: next journey, owner and invitation')]},
 catalytic:{group:'sunday',type:'service',title:'Catalytic Sunday pack',fields:[f('bigIdea','Big idea'),f('scripture','Scripture and translation'),f('outline','Teaching outline'),f('illustration','Illustrations and source citations'),f('gospel','Gospel explanation'),f('response','Response moment'),field('nextStep','Primary next step',['Join a group','Serve','Give','Baptism conversation','Invite someone','Start a campaign']),f('callToAction','Clear invitation and how to respond'),f('card','Communication card text'),f('followup','Follow-up pathway, owner and timing'),f('reviewer','Teaching reviewer','text')]},
 service:{group:'sunday',type:'service',title:'Weekend service run sheet',fields:[f('date','Service date','date'),f('startTime','Start time','time'),f('runSheet','Run sheet: one line per item, minutes | moment | owner'),f('welcome','Welcome script'),f('transitions','Transition scripts'),f('worship','Worship moments and licensed-song references'),f('bulletin','Bulletin insert'),f('social','Social copy and clip timecodes'),f('nextSteps','Next steps and response team')]},
 calendar:{group:'sunday',type:'calendar',title:'Annual formation plan',fields:[f('year','Year','number'),f('winter','New year / winter pathway, owner, milestones'),f('easter','Lent / Easter pathway, owner, milestones'),f('summer','Summer pathway, owner, milestones'),f('fall','Fall launch pathway, owner, milestones'),f('advent','Advent pathway, owner, milestones'),f('leaders','Leader development rhythm'),f('continuation','Day 41 and group continuation'),f('reviewDates','Review dates and evidence to discuss')]},
 mission:{group:'tools',type:'tool',title:'Family mission builder',fields:[f('stories','When have we been at our best together?'),f('values','Three values we want our choices to express'),f('people','Who are we here to love and serve?'),f('statement','Our family mission in one or two sentences'),f('practice','One weekly practice that makes the mission visible'),f('review','When will we revisit this?','date')]},
 giving:{group:'tools',type:'tool',title:'Family giving plan',fields:[f('purpose','Why we want to give'),f('causes','People, ministries and causes we want to understand'),f('resources','Time, skills and resources available'),f('decisions','How we will make decisions together'),f('plan','Commitment, recipient, owner and review date'),f('questions','Questions for a qualified advisor')]},
 meeting:{group:'tools',type:'tool',title:'Family meeting agenda',fields:[f('date','Meeting date','date'),f('host','Host','text'),f('welcome','Opening gratitude and check-in'),f('story','A family story to hear'),f('discussion','One meaningful question to discuss'),f('decision','Decisions and unresolved questions'),f('actions','Next action, owner and date'),f('closing','Closing prayer / reflection')]},
 legacy:{group:'tools',type:'tool',title:'Legacy roadmap',fields:[f('vision','What we hope to pass on'),f('stories','Stories to preserve and whose consent is needed'),f('relationships','Relationships to strengthen'),f('skills','Wisdom and responsibilities to practice'),f('steps','30-, 90- and 365-day steps'),f('owners','Owners and review dates')]},
 heirs:{group:'tools',type:'tool',title:'Next-generation readiness conversation',fields:[f('strengths','Strengths each person sees in themselves'),f('experience','Responsibilities they have practiced'),f('learning','What they want to learn next'),f('support','Support, mentors and boundaries'),f('practice','One safe practice opportunity'),f('review','What we will learn from the experience')]},
 constitution:{group:'tools',type:'tool',title:'Family commitments & governance',fields:[f('purpose','Shared purpose'),f('values','Values and practical commitments'),f('participation','Who participates, and how voices are heard'),f('decisions','How decisions are made'),f('conflict','How we handle disagreement'),f('privacy','Consent and privacy commitments'),f('review','Review rhythm and professional questions')]},
 advisorConversation:{group:'tools',type:'tool',title:'Advisor conversation guide',fields:[f('goals','What matters most to our family'),f('questions','Questions about credentials, scope, fees and conflicts'),f('permission','Information we are willing to share'),f('boundaries','Information we are keeping private'),f('followup','Agreed scope, actions and next meeting')]},
 source:{group:'sources',type:'source',title:'Sermon / media intake',fields:[field('layer','Intelligence library',['My sermon intelligence','LifeTogether intelligence','Global church reference']),f('author','Author / speaker','text'),f('sourceUrl','Original source URL','url'),f('date','Original date','date'),f('scripture','Scripture reference and translation'),f('transcript','Transcript / sermon text'),f('timecodes','Media timecodes and recovery notes'),field('permission','Use permission',['Unknown — hold','Owned by our church / author','Written permission supplied','Reference only']),f('rightsEvidence','Permission evidence and contact / agreement reference'),field('adaptation','Adaptation rights',['Not verified','Granted','Not granted']),field('commercial','Commercial rights',['Not verified','Granted','Not granted']),field('print','Print rights',['Not verified','Granted','Not granted']),f('citation','Citation to carry into outputs')]},
 edition:{group:'sources',type:'edition',title:'Personalized edition',fields:[field('mode','Edition mode',['ready-made','personalize','full-custom']),f('sourceIds','Source IDs and permission references'),f('protectedCore','Protected author / theological core'),f('localTitle','Local title','text'),f('subtitle','Local subtitle','text'),f('foreword','Local foreword'),f('stories','Local stories with permission'),f('branding','Church / advisor branding and cover direction'),f('changes','Requested changes to protected content for reviewer'),f('reviewer','Reviewer','text'),field('review','Review status',['Draft','Editorial review','Theological review','Approved internally'])]},
 contribution:{group:'sources',type:'contribution',title:'Contributor review',fields:[f('author','Contributor / rights holder','text'),f('sourceUrl','Source file or media URL','url'),f('inventory','Supplied files, transcripts and missing material'),f('rightsEvidence','Written permission evidence'),field('adaptation','Adaptation rights',['Not verified','Granted','Not granted']),field('commercial','Commercial rights',['Not verified','Granted','Not granted']),field('print','Print rights',['Not verified','Granted','Not granted']),f('editorial','Editorial findings and reviewer'),f('theology','Theological findings and reviewer'),field('status','Production status',['Intake','Rights hold','Editing','Review','Ready for publishing review']),f('releaseNotes','Version notes and remaining release decisions')]},
 hosts:{group:'ministry',type:'ministry',title:'Group host recruitment & coaching',fields:[f('goal','Groups and leaders needed'),f('invitation','Host invitation and expectations'),f('training','Training and first-session practice'),f('coaching','Coach assignments and check-in rhythm'),f('care','Care and escalation contacts'),f('continuation','Completion and next-group invitation'),f('actions','Action | owner | due date | status')]},
 volunteers:{group:'ministry',type:'ministry',title:'Volunteer & staff alignment',fields:[f('mission','Shared purpose'),f('roles','Role | responsibilities | owner'),f('recruitment','Recruitment and welcome steps'),f('training','Training and safeguarding requirements'),f('rhythm','Team meetings, coaching and appreciation'),f('actions','Action | owner | due date | status')]},
 ministryLaunch:{group:'ministry',type:'ministry',title:'Ministry launch pathway',fields:[field('ministry','Ministry',['Family legacy','Generosity & financial wisdom','Marketplace','Leadership development','Small groups']),f('purpose','Who we serve and the change we hope for'),f('champion','Ministry champion and team'),f('pilot','Pilot cohort and listening plan'),f('resources','Approved resources and content gaps'),f('launch','Recruitment, training, launch and follow-up dates'),f('evidence','What we will observe and learn'),f('actions','Action | owner | due date | status')]},
 advisorIntake:{group:'advisors',type:'referral',title:'Advisor practice profile',fields:[f('practice','Practice name','text'),f('region','Region and meeting formats'),f('specialties','Areas of practice and audience'),f('credentials','Credentials with public verification URLs'),f('fees','Fee model and potential conflicts'),f('scope','Services and limits'),field('verification','Verification status',['Not verified','Evidence collected','Independent review needed']),f('workshops','Workshop / church partnership plan')]},
 familyIntake:{group:'advisors',type:'referral',title:'Family referral & engagement',fields:[f('region','Region and meeting preference'),f('needs','Guidance needed'),f('criteria','Credentials, specialty, fees and relationship preferences'),f('consent','What the family explicitly permits sharing'),f('advisor','Advisor selected by the family'),field('status','Referral status',['Preparing brief','Reviewing candidates','Introduction requested','Meeting scheduled','Engaged','Closed']),f('nextAction','Next action, owner and date'),f('gift','Co-branded gift plan and approved budget')]}
};
export function blankRecipe(key){const r=recipes[key];if(!r)throw Error('Unknown tool');return {title:r.title,type:r.type,visibility:'private',content:{recipe:key,...Object.fromEntries(r.fields.map(x=>[x.key,x.type==='select'?x.options[0]:''])),...(key==='campaign'?{days:'21',sessions:'3',mode:'Churchwide',customization:'Personalize'}:{})}}}
export function timeline(raw,startTime='09:00') {const [hh,mm]=startTime.split(':').map(Number);let offset=Number.isFinite(hh+mm)?hh*60+mm:540;return String(raw||'').split('\n').filter(x=>x.trim()).map((line,i)=>{const [duration,label,owner]=line.split('|').map(x=>x.trim()),minutes=Number(duration);if(!Number.isFinite(minutes)||minutes<=0||minutes>240)throw Error('Line '+(i+1)+': begin with minutes between 1 and 240.');const start=`${String(Math.floor(offset/60)%24).padStart(2,'0')}:${String(offset%60).padStart(2,'0')}`;offset+=minutes;return {start,minutes,moment:label||'Service moment',owner:owner||''}})}
export function documentText(doc){const r=recipes[doc.content.recipe];return '# '+doc.title+'\n\n'+(r?r.fields.map(f=>'## '+f.label+'\n\n'+String(doc.content[f.key]||'Not yet supplied')).join('\n\n'):JSON.stringify(doc.content,null,2))+'\n\n---\nSaved version: '+(doc.version||'unsaved')+'\nThis working document requires the appropriate source, teaching and production review before publication.\n'}
export function ministryChecklist(raw){return String(raw||'').split('\n').filter(Boolean).map(line=>{const [action,owner,due,status]=line.split('|').map(s=>s.trim());return {action,owner:owner||'Unassigned',due:due||'',status:roles.includes(status)?status:'Not started'}})}
