import {inspectPDF,openPDF} from './production.mjs';
const sites=[['Sermon Curator','sermon-curator'],['Small Group Curriculum','small-group-curriculum'],['Christian Advisor Network','christian-advisor-network'],['40 Day Campaign','40-day-campaign'],['Family Legacy Ministry','family-legacy-ministry'],['Financial Wisdom Ministry','financial-wisdom-ministry'],['Family Legacy by Design','family-legacy-by-design'],['Flourishing Life','flourishing-life-series'],['Christian Marketplace','christian-marketplace'],['Doing Church Together','doing-church-together']];
export function createStudio(ctx){
 const {E,frame,api,message,guarded,download,printAPI}=ctx;let health={},proof=null,pdfBytes=null,report=null,fileKind='',uploaded={},uploadTitle='',mediaResult=null,currentBrand=null;
 const state=()=>ctx.state(),docs=()=>state().workspace.documents,find=id=>docs().find(d=>d.id===id),button=(label,action,extra='')=>`<button type="button" data-studio="${action}" ${extra}>${label}</button>`;
 const input=(name,label,value='',type='text',extra='')=>`<label class="workspace-field"><span>${E(label)}</span><input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`;
 const area=(name,label,value='',extra='')=>`<label class="workspace-field"><span>${E(label)}</span><textarea name="${name}" rows="7" ${extra}>${E(value)}</textarea></label>`;
 const select=(name,label,options,value='')=>`<label class="workspace-field"><span>${E(label)}</span><select name="${name}">${options.map(([id,title])=>`<option value="${E(id)}" ${id===value?'selected':''}>${E(title)}</option>`).join('')}</select></label>`;
 const check=(name,label)=>`<label class="studio-check"><input name="${name}" type="checkbox" required><span>${label}</span></label>`;
 const writable=()=>['owner','editor'].includes(state().workspace.members[state().user.id].role);
 const texts=d=>d.content.recipe==='reader'?d.content.days.map(x=>`Day ${x.day}: ${x.title}\n${x.scripture}\n${x.body}\n${x.practice||''}`).join('\n\n'):d.content.transcript||d.content.body||Object.entries(d.content).filter(([k,v])=>k!=='recipe'&&typeof v==='string').map(([k,v])=>`${k}: ${v}`).join('\n\n');
 const docOptions=()=>docs().filter(d=>!['brand','delivery','progress','reflection'].includes(d.type)).map(d=>[d.id,d.title]);
 async function connected(action,body={}){const r=await fetch('/.netlify/functions/studio',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,workspace:state().workspace.id,...body})}),d=await r.json();if(!r.ok)throw Error(d.error);return d;}
 async function save(type,title,content,old=null){return (await api('save',{document:{...old,type,title,visibility:old?.visibility||'workspace',content}})).document;}
 function heading(kicker,title,description){return `<span class="eyebrow">${kicker}</span><h1>${title}</h1><p class="workspace-lead">${description}</p>`;}
 function setup(){return `<details class="workspace-panel"><summary>Connected services & setup</summary><p>Set these server-only variables on <a href="https://app.netlify.com/projects/lifetogether-doing-church-together/configuration/env" target="_blank" rel="noopener">Doing Church Together in Netlify</a>, then redeploy. Never put keys in a document.</p><ul><li>Transcription: ASSEMBLYAI_API_KEY — ${health.transcription?'configured':'not connected'}</li><li>Translation & sermon suggestions: OPENAI_API_KEY and STUDIO_TEXT_MODEL — ${health.writing?'configured':'not connected'}</li><li>Email: RESEND_API_KEY and CAMPAIGN_FROM_EMAIL — ${health.email?'configured':'not connected'}</li><li>SMS: TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN and TWILIO_MESSAGING_SERVICE_SID — ${health.sms?'configured':'not connected'}</li><li>CAMPAIGN_DELIVERY_ENABLED=true enables scheduled sending after your sender accounts are ready. Current status: ${health.deliveryEnabled?'enabled':'off'}.</li></ul><p>Connected services process only material you explicitly submit. Review generated text before publishing.</p></details>`;}
 function dashboard(){const {workspace,user}=state(),reviews=workspace.reviews||[],pending=reviews.filter(r=>r.kind==='request'&&r.assignee===user.id&&docs().some(d=>d.id===r.document&&d.version===r.version)&&!reviews.some(v=>v.document===r.document&&v.version===r.version&&['approve','changes'].includes(v.kind)&&v.at>=r.at));
 frame(heading('YOUR MINISTRY DESK','Pick up where<br><em>purpose left off.</em>','One shared workspace for your library, production, team, and every LifeTogether website.')+`<div class="studio-next"><strong>${pending.length?`${pending.length} review request${pending.length===1?'':'s'} waiting for you`:'Ready for your next step'}</strong><a href="#/reviews">Open team reviews →</a></div><div class="workspace-cards studio-tools">${[['production','01','Proof & print','Upload files, inspect pages, and prepare a print edition.'],['sermon-intake','02','Sermon intelligence','Transcribe a recording and organize your teaching.'],['branding','03','Church branding','Carry your identity into guides, covers and invitations.'],['bilingual','04','Bilingual editions','Keep English and Spanish teaching connected.'],['delivery','05','Campaign delivery','Prepare consent-based email and text schedules.'],['reviews','06','Team reviews','Comments, assignments and version-specific approvals.']].map(([r,n,t,p])=>`<a href="#/${r}"><small>${n}</small><h2>${t}</h2><p>${p}</p><span>Open studio →</span></a>`).join('')}</div><section class="workspace-panel"><h2>Continue recent work</h2>${docs().slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,6).map(d=>`<a class="studio-recent" href="#/${d.type==='bilingual'?'bilingual':d.type==='brand'?'branding':d.content.recipe==='reader'?'reader':'document'}/${d.id}"><strong>${E(d.title)}</strong><span>${E(d.type)} · ${new Date(d.updatedAt).toLocaleDateString()}</span></a>`).join('')||'<p>Your saved documents will appear here.</p>'}</section><section class="workspace-panel"><h2>Every ministry, connected</h2><div class="studio-network"><a href="https://lifetogethermasterlibary.netlify.app/#/home">Master library ↗</a>${sites.map(([title,slug])=>`<a href="https://lifetogether-${slug}.netlify.app/">${title} ↗</a>`).join('')}</div></section>`,'Ministry dashboard');}
 function production(){frame(heading('FROM MANUSCRIPT TO MINISTRY','A book you can<br><em>review with confidence.</em>','Drop a PDF, inspect its actual pages, and create a printer-accessible link after review.')+`<section class="workspace-panel"><form id="studio-proof"><div class="workspace-fields">${input('title','Book title',uploadTitle,'text','required maxlength="200"')}${select('kind','File type',[['interior','Interior pages'],['cover','Full cover spread']])}${input('pages','Expected interior page count','','number','min="1" max="3000"')}${select('size','Interior dimensions',[['6.25x9.25','6 × 9 trim with bleed (6.25 × 9.25 PDF)'],['6x9','6 × 9, no bleed'],['custom','Custom dimensions']])}${input('width','Custom width (inches)',6.25,'number','min="1" max="30" step=".001"')}${input('height','Custom height (inches)',9.25,'number','min="1" max="30" step=".001"')}</div><label class="studio-drop" id="studio-drop"><strong>Drop your PDF here</strong><span>or choose a file · up to 3 MB for hosted printer links</span><input type="file" name="pdf" accept="application/pdf,.pdf" required></label><button class="workspace-primary">Check file & open proof →</button></form></section><div id="studio-proof-result"></div><div id="studio-print-pair">${pairView()}</div><section class="workspace-panel"><h2>Your saved files</h2><a href="#/print-files">Manage hosted files, expiry dates & revocation →</a></section>`,'Proof studio');}
 function pairView(){return `<section class="workspace-panel"><h2>Build your print edition</h2><p>${uploaded.interior?'✓ Interior connected':'○ Upload and review an interior'} · ${uploaded.cover?'✓ Cover connected':'○ Upload and review a cover'}</p>${uploaded.interior&&uploaded.cover?button('Continue to shipping & price','handoff','class="workspace-primary"'):'<p>After reviewing both files, continue directly to the print estimate with their links and page count attached.</p>'}<p class="workspace-caption">A screen proof is a layout check. Approve a physical copy before a full production run.</p></section>`;}
 async function previewFile(form,file){if(!file||file.size>700000)throw Error('Choose a PDF under 3 MB.');const f=Object.fromEntries(new FormData(form));fileKind=f.kind;if(uploadTitle&&uploadTitle!==f.title.trim())uploaded={};uploadTitle=f.title.trim();if(!uploadTitle)throw Error('Add the book title.');pdfBytes=new Uint8Array(await file.arrayBuffer());const size=f.size==='custom'?[Number(f.width),Number(f.height)]:f.size.split('x').map(Number);report=await inspectPDF(pdfBytes,{kind:fileKind,width:size[0],height:size[1],expectedPages:Number(f.pages)||0});
 document.querySelector('#studio-proof-result').innerHTML=`<section class="workspace-panel"><span class="eyebrow">FILE CHECK</span><h2>${report.errors.length?'Fix these items before printing':'Structure check complete'}</h2><p>${report.pageCount} pages · ${report.dimensions.width.toFixed(3)} × ${report.dimensions.height.toFixed(3)} inches</p><ul>${report.errors.map(x=>`<li class="studio-error">${E(x)}</li>`).join('')}${report.warnings.map(x=>`<li>${E(x)}</li>`).join('')}</ul><div class="studio-proof-controls">${button('← Previous page','proof-previous')}${button('Next page →','proof-next')}<span id="studio-page-label" aria-live="polite"></span><label>Go to page <input id="studio-page-number" type="number" min="1" max="${report.pageCount}" value="1"></label>${button('Go','proof-go')}</div><div class="studio-canvas"><canvas id="studio-pdf-canvas" aria-label="PDF page preview"></canvas></div><form id="studio-upload">${check('review','I reviewed this file, have permission to print it, and approve a printer link that expires after 90 days.')}${input('reviewNote','Proof review note','','text','required maxlength="500" placeholder="e.g. Checked headings, trim and all pages"')}<button class="workspace-primary" ${report.errors.length?'disabled':''}>Save reviewed PDF & create printer link →</button></form></section>`;
 await proof?.destroy();proof=await openPDF(pdfBytes,document.querySelector('#studio-pdf-canvas'),document.querySelector('#studio-page-label'));document.querySelector('#studio-proof-result').scrollIntoView({behavior:'smooth'});
 }
 function branding(){const d=docs().find(x=>x.type==='brand');currentBrand=d;const b=d?.content||{name:state().workspace.name,primary:'#233c35',accent:'#b97547',font:'Manrope',tagline:'Life is better together.',wording:''};frame(heading('YOUR CHURCH, RECOGNIZABLY YOURS','One identity.<br><em>Every invitation.</em>','Save an approved brand kit, then export coordinated campaign assets.')+`<form id="studio-brand" class="workspace-panel"><div class="workspace-fields">${input('name','Church / ministry name',b.name,'text','required maxlength="120"')}${input('tagline','Tagline',b.tagline,'text','maxlength="200"')}${input('primary','Primary color',b.primary,'color')}${input('accent','Accent color',b.accent,'color')}${select('font','Typography',[['Manrope','Manrope · warm modern'],['DM Serif','DM Serif · editorial']],b.font)}<label class="workspace-field"><span>Logo (PNG / JPEG, under 70 KB)</span><input type="file" name="logo" accept="image/png,image/jpeg"></label></div>${b.logo?`<img class="studio-logo" src="${E(b.logo)}" alt="Saved church logo">`:''}${area('wording','Approved wording / invitation',b.wording,'maxlength="4000"')}<button class="workspace-primary">Save brand kit →</button></form><section class="workspace-panel"><h2>Create a matching asset set</h2><form id="studio-brand-export">${input('title','Campaign title','','text','required maxlength="150"')}${input('subtitle','Subtitle','','text','maxlength="250"')}${input('details','Date, location & next step','','text','maxlength="400"')}${select('document','Participant guide source (optional)',[['','Title page only'],...docOptions()])}<button class="workspace-primary" ${d?'':'disabled'}>Download branded asset pack →</button></form><p>Includes a front-cover concept, a participant guide, a presentation slide, and an invitation. The cover concept needs a complete Lulu wrap template before printing.</p></section>`,'Church branding');}
 function intake(){frame(heading('YOUR TEACHING, READY TO BUILD ON','From spoken word<br><em>to searchable source.</em>','Transcribe your recording, review the text, and save it with clear authorship and permission details.')+`<section class="workspace-panel"><form id="studio-transcribe">${input('title','Working sermon title','','text','required maxlength="200"')}${input('url','Direct HTTPS audio or video file URL','','url')}<p>Use an MP3/MP4 download link. For YouTube or Vimeo, export your owned recording or use its original media file.</p><label class="workspace-field"><span>Or upload a recording (under 3 MB; use a direct URL for longer sermons)</span><input name="audio" type="file" accept="audio/*,video/mp4"></label>${check('confirm','I have permission to send this recording to the connected transcription service.')}<button class="workspace-primary" ${health.transcription?'':'disabled'}>Start transcription →</button></form><p>${health.transcription?'Transcription runs in the background. Keep the job ID to resume it.':'Transcription needs the AssemblyAI account connection. You can paste and save a transcript below now.'}</p><form id="studio-transcript-status">${input('job','Resume transcription job','','text','required')}<button>Check transcript status</button></form></section><section class="workspace-panel"><h2>Review and save your source</h2><form id="studio-sermon">${input('title','Sermon title',mediaResult?.title||'','text','required maxlength="200"')}${input('subtitle','Subtitle','','text','maxlength="300"')}${input('speaker','Speaker / author','','text','required maxlength="200"')}${input('scripture','Scripture references','','text','maxlength="1000"')}${input('themes','Themes','','text','maxlength="1000"')}${area('transcript','Reviewed transcript',mediaResult?.text||'','required maxlength="100000"')}${select('rights','Permission to use this teaching',[['Reference only','Reference only'],['Our original teaching','Our original teaching'],['Permission granted','Permission granted']])}<div class="workspace-actions">${button('Suggest title, subtitle & themes','sermon-suggest',health.writing?'':'disabled')}<button class="workspace-primary">Save reviewed source →</button></div></form><div id="studio-suggestions" aria-live="polite"></div></section>${setup()}`,'Sermon intake');}
 function bilingual(id){const d=find(id),c=d?.type==='bilingual'?d.content:null;if(!c){frame(heading('ENGLISH + ESPAÑOL','The same message.<br><em>More people included.</em>','Create a linked bilingual edition with a preserved source and a separate translation review.')+`<form id="studio-bilingual-new" class="workspace-panel">${select('source','Source document',docOptions())}${select('language','Translate into',[['Spanish','Spanish'],['English','English']])}<button class="workspace-primary">Create paired edition →</button></form><section class="workspace-panel"><h2>Your bilingual editions</h2>${docs().filter(x=>x.type==='bilingual').map(x=>`<a class="studio-recent" href="#/bilingual/${x.id}">${E(x.title)}</a>`).join('')||'<p>No paired editions yet.</p>'}</section>`,'Bilingual editions');return}
 const source=find(c.sourceId),stale=source&&source.version!==c.sourceVersion;frame(heading('LINKED LANGUAGE EDITION',E(d.title),'The source stays intact. Review the translation beside it before requesting team approval.')+`${stale?'<p class="studio-error">The source document has changed. This edition still uses the recorded source version. Start a new paired edition to translate the updated source.</p>':''}<form id="studio-bilingual" data-id="${d.id}" class="workspace-panel">${area('glossary','Shared terminology: source term = translated term',c.glossary||'','maxlength="4000"')}<div class="studio-bilingual"><section><h2>Source · version ${c.sourceVersion}</h2><pre>${E(c.sourceText)}</pre></section><section><h2>${E(c.language)} · working draft</h2>${area('translation','Translation',c.translation||'','maxlength="100000"')}</section></div><div class="workspace-actions">${button('Generate translation draft','translate',health.writing?'':'disabled')}<button class="workspace-primary">Save paired edition →</button><a href="#/reviews/${d.id}">Request translation review →</a>${button('Export bilingual text','bilingual-export',`data-id="${d.id}"`)}</div><p>Generated translations need a fluent reviewer and pastoral approval. Changing either document requires a new review.</p></form>${setup()}`,'Bilingual review');}
 function reviews(id){const available=docOptions(),d=find(id)||find(available[0]?.[0]),{workspace,user}=state();if(!d){frame('<h1>Team reviews</h1><p>Save a source or campaign document first.</p>');return}const events=(workspace.reviews||[]).filter(x=>x.document===d.id);frame(heading('WORK TOGETHER WITH CLARITY','The right eyes.<br><em>The right version.</em>','Comments, revision requests and approvals stay attached to the exact saved version.')+`<label class="workspace-field"><span>Document</span><select id="studio-review-document">${available.map(([id,title])=>`<option value="${id}" ${id===d.id?'selected':''}>${E(title)}</option>`).join('')}</select></label><section class="workspace-panel"><h2>${E(d.title)} · version ${d.version}</h2><details><summary>Read the saved text</summary><pre>${E(texts(d))}</pre></details><form id="studio-review" data-id="${d.id}" data-version="${d.version}">${select('kind','Review action',writable()?[['comment','Leave a comment'],['request','Request approval'],['changes','Request changes'],['approve','Approve this version']]:[['comment','Leave a comment']])}${select('assignee','Assign approval to',Object.entries(workspace.members).filter(([,m])=>['owner','editor'].includes(m.role)).map(([id,m])=>[id,m.name]))}${input('passage','Passage or page reference (optional)','','text','maxlength="1000"')}${area('message','Review note','','required maxlength="4000"')}<button class="workspace-primary">Save review →</button></form></section><section class="workspace-panel"><h2>Review activity</h2>${events.slice().reverse().map(r=>`<article class="studio-review"><span class="eyebrow">${E(r.kind)} · VERSION ${r.version}${r.version!==d.version?' · PREVIOUS VERSION':''}</span><p>${E(r.message)}</p>${r.passage?`<blockquote>${E(r.passage)}</blockquote>`:''}<small>${E(workspace.members[r.actor]?.name||'Former member')} · ${E(new Date(r.at).toLocaleString())}${r.assignee?' · Assigned to '+E(workspace.members[r.assignee]?.name||'Former member'):''}</small></article>`).join('')||'<p>No reviews recorded yet.</p>'}</section>`,'Team reviews');}
 async function route(r,id){if(!['dashboard','production','branding','sermon-intake','bilingual','reviews','delivery'].includes(r))return false;if(proof){await proof.destroy();proof=null}if(['sermon-intake','bilingual','delivery'].includes(r))health=await connected('health');if(r==='dashboard')dashboard();if(r==='production')production();if(r==='branding')branding();if(r==='sermon-intake')intake();if(r==='bilingual')bilingual(id);if(r==='reviews')reviews(id);if(r==='delivery')await ctx.delivery({E,frame,message,guarded,download,health,setup,state,docs,api,input,area,select,check,heading});return true;}
 document.addEventListener('submit',e=>{if(!e.target.id?.startsWith('studio-')||e.target.id.startsWith('studio-delivery'))return;e.preventDefault();e.stopImmediatePropagation();const form=e.target;guarded(async()=>{const f=Object.fromEntries(new FormData(form));
 if(form.id==='studio-proof')await previewFile(form,form.elements.pdf.files[0]);
 if(form.id==='studio-upload'){if(!report||report.errors.length||!pdfBytes)throw Error('Check a valid PDF first.');if(!f.review)throw Error('Confirm your file review first.');let binary='';for(let i=0;i<pdfBytes.length;i+=8192)binary+=String.fromCharCode(...pdfBytes.slice(i,i+8192));const result=await printAPI('upload',{title:uploadTitle,kind:fileKind,pdf:btoa(binary),confirm:true,reviewNote:f.reviewNote,preflight:report});uploaded[fileKind]=result;document.querySelector('#studio-print-pair').innerHTML=pairView();message('Reviewed file saved. Printer link expires in 90 days.');}
 if(form.id==='studio-brand'){let logo=currentBrand?.content.logo||'';const file=form.elements.logo.files[0];if(file){if(file.size>70000||!['image/png','image/jpeg'].includes(file.type))throw Error('Use a PNG or JPEG under 70 KB.');logo=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});if(logo.length>100000)throw Error('Use a smaller logo (about 70 KB) so the complete brand kit fits the workspace.');}await save('brand',f.name+' brand kit',{name:f.name,tagline:f.tagline,primary:f.primary,accent:f.accent,font:f.font,wording:f.wording,logo},currentBrand);branding();message('Brand kit saved for your workspace.');}
 if(form.id==='studio-brand-export'){const {brandAssets}=await import('./brand-assets.js');await brandAssets(currentBrand.content,f,find(f.document),download);message('Your branded asset ZIP has downloaded with four coordinated PDFs.');}
 if(form.id==='studio-transcribe'){const file=form.elements.audio.files[0];let audio;if(file){if(file.size>700000)throw Error('Use a recording under 3 MB or a direct URL.');const bytes=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.slice(i,i+8192));audio=btoa(raw);}const d=await connected('transcribe',{url:f.url,audio,confirm:Boolean(f.confirm)});document.querySelector('#studio-transcript-status [name="job"]').value=d.id;mediaResult={title:f.title,text:''};message('Transcription started. Job '+d.id+'. Select Check transcript status in a moment.');}
 if(form.id==='studio-transcript-status'){const d=await connected('transcript-status',{id:f.job.trim()});if(d.status==='completed'){mediaResult={...mediaResult,text:d.text};intake();message('Transcript ready. Review the words and save your source.');}else if(d.status==='error')throw Error(d.error);else message('Transcription is '+d.status+'. Check again shortly.');}
 if(form.id==='studio-sermon'){await save('source',f.title,{recipe:'source',author:f.speaker,subtitle:f.subtitle,scripture:f.scripture,themes:f.themes,transcript:f.transcript,permission:({'Our original teaching':'Owned by our church / author','Permission granted':'Written permission supplied'})[f.rights]||'Reference only',adaptation:'Not verified',commercial:'Not verified',print:'Not verified',rights:f.rights,sourceType:'Reviewed sermon transcript'});message('Sermon saved in the shared source library.');}
 if(form.id==='studio-bilingual-new'){const source=find(f.source);if(!source)throw Error('Choose a source document.');const d=await save('bilingual',source.title+' · '+f.language,{sourceId:source.id,sourceVersion:source.version,sourceText:texts(source),language:f.language,translation:'',glossary:''},{visibility:source.visibility});location.hash='/bilingual/'+d.id;}
 if(form.id==='studio-bilingual'){const d=find(form.dataset.id);await save('bilingual',d.title,{...d.content,translation:f.translation,glossary:f.glossary},d);message('Translation saved. Request review of this version when ready.');}
 if(form.id==='studio-review'){await api('review',{document:form.dataset.id,version:Number(form.dataset.version),kind:f.kind,assignee:f.assignee,message:f.message,passage:f.passage});reviews(form.dataset.id);message('Review saved against the current document version.');}
 });},true);
 document.addEventListener('change',e=>{if(e.target.id==='studio-review-document')location.hash='/reviews/'+e.target.value;});
 document.addEventListener('dragover',e=>{if(e.target.closest('#studio-drop')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});
 document.addEventListener('drop',e=>{const drop=e.target.closest('#studio-drop');if(!drop)return;e.preventDefault();const form=document.querySelector('#studio-proof');if(form)guarded(()=>previewFile(form,e.dataTransfer.files[0]));});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-studio]');if(!b)return;e.preventDefault();guarded(async()=>{const action=b.dataset.studio;
 if(action==='proof-next')await proof?.next();if(action==='proof-previous')await proof?.previous();if(action==='proof-go')await proof?.draw(document.querySelector('#studio-page-number').value);
 if(action==='handoff'){const draft={title:uploadTitle,page_count:uploaded.interior.file.pageCount,interior_url:uploaded.interior.url,cover_url:uploaded.cover.url,retail_price:'0.00',status:'files'};location.href='https://lifetogethermasterlibary.netlify.app/#/print-studio?edit=new&draft='+encodeURIComponent(JSON.stringify(draft));}
 if(action==='sermon-suggest'){const form=document.querySelector('#studio-sermon'),d=await connected('suggest',{text:form.elements.transcript.value,confirm:true});let s;try{s=JSON.parse(d.text)}catch{throw Error('Suggestions could not be read. Try again.');}document.querySelector('#studio-suggestions').innerHTML=`<h3>Editorial suggestions · review before using</h3><pre>${E(JSON.stringify(s,null,2))}</pre>${button('Apply suggestions to this draft','apply-suggestions')}`;mediaResult={...mediaResult,suggestions:s};}
 if(action==='apply-suggestions'){const f=document.querySelector('#studio-sermon'),s=mediaResult.suggestions;for(const key of ['title','subtitle','scripture','themes'])if(s[key]!=null)f.elements[key].value=Array.isArray(s[key])?s[key].join(', '):s[key];message('Suggestions applied. Review and save when ready.');}
 if(action==='translate'){const form=document.querySelector('#studio-bilingual'),d=find(form.dataset.id),result=await connected('translate',{text:d.content.sourceText,language:d.content.language,glossary:form.elements.glossary.value,confirm:true});form.elements.translation.value=result.text;message('Translation draft ready. Review and save it; it is not approved.');}
 if(action==='bilingual-export'){const d=find(b.dataset.id);download('bilingual-edition.md',`# ${d.title}\n\nSource version ${d.content.sourceVersion}\n\n## Source\n${d.content.sourceText}\n\n## ${d.content.language}\n${d.content.translation}\n\n## Glossary\n${d.content.glossary}\n\nReview status: see version-specific Team reviews.`);}
 });});
 return {route,dashboard};
}
