import {getUser,verifyRequestOrigin,refreshSession} from '@netlify/identity';import {getStore} from '@netlify/blobs';
import {digest,validateCampaign,newSubscription} from './delivery-core.mjs';
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
const id=v=>/^[a-zA-Z0-9-]{1,100}$/.test(v||'')?v:fail('Invalid identifier.');
const ready=channel=>channel==='email'?Boolean(process.env.RESEND_API_KEY&&process.env.CAMPAIGN_FROM_EMAIL):Boolean(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_MESSAGING_SERVICE_SID);
export default async request=>{const headers={'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'},store=getStore({name:'lifetogether-delivery-v1',consistency:'strong'});try{
 const url=new URL(request.url);
 if(url.searchParams.get('unsubscribe')){
  const key=id(url.searchParams.get('unsubscribe')),token=url.searchParams.get('token'),s=await store.get('subscribers/'+key,{type:'json'});if(!s||!token||digest(s.token)!==digest(token))fail('This preference link is unavailable.',404);
  if(request.method==='GET')return new Response('<!doctype html><meta name="viewport" content="width=device-width"><title>LifeTogether delivery preferences</title><main style="max-width:36rem;margin:12vh auto;padding:2rem;font:18px system-ui"><h1>Stop campaign messages?</h1><p>This stops campaign email and text messages from this workspace. Your account stays active.</p><form method="post"><button style="padding:1rem">Unsubscribe from this workspace</button></form></main>',{headers:{...headers,'Content-Type':'text/html; charset=utf-8'}});
  if(request.method!=='POST')fail('Use POST.',405);await store.setJSON('subscribers/'+key,{...s,emailOptIn:false,smsOptIn:false,unsubscribedAt:new Date().toISOString()});return new Response('You are unsubscribed from this workspace’s campaign messages.',{headers});
 }
 if(request.method!=='POST')fail('Use POST.',405);verifyRequestOrigin(request);await refreshSession();const user=await getUser();if(!user)fail('Sign in to manage campaign delivery.',401);const raw=await request.text();if(raw.length>280000)fail('Split this campaign into smaller message schedules.',413);const body=JSON.parse(raw),workspace=id(body.workspace),ws=await getStore({name:'lifetogether-platform-v1',consistency:'strong'}).get('workspaces/'+workspace,{type:'json'}),role=ws?.members[user.id]?.role;if(!role)fail('Workspace unavailable.',404);
 const key=digest(workspace+'|'+user.id),old=await store.get('subscribers/'+key,{type:'json'}),self=old||newSubscription(user,workspace),admin=['owner','editor'].includes(role);
 if(body.action==='list'){const campaigns=[];if(admin){const list=await store.list({prefix:'campaigns/'});for(const entry of list.blobs){const c=await store.get(entry.key,{type:'json'});if(c.workspace===workspace)campaigns.push(c)}}const subscriptions=await store.list({prefix:'subscribers/'});let email=0,sms=0;for(const entry of subscriptions.blobs){const s=await store.get(entry.key,{type:'json'});if(s.workspace===workspace&&ws.members[s.user]){if(s.emailOptIn)email++;if(s.smsOptIn)sms++;}}return Response.json({campaigns,counts:{email,sms},preferences:{emailOptIn:self.emailOptIn,smsOptIn:self.smsOptIn,phone:self.phone||''},admin,ready:{email:ready('email'),sms:ready('sms'),smsVerification:Boolean(process.env.TWILIO_VERIFY_SERVICE_SID)},enabled:process.env.CAMPAIGN_DELIVERY_ENABLED==='true'},{headers});}
 if(body.action==='preferences'){if(body.emailOptIn===true&&body.confirm!==true)fail('Confirm that you want campaign email.');const next={...self,email:user.email,emailOptIn:body.emailOptIn===true,emailConsentedAt:body.emailOptIn?(self.emailOptIn?self.emailConsentedAt:new Date().toISOString()):self.emailConsentedAt,consentText:body.emailOptIn?'I choose campaign emails from this workspace and can unsubscribe at any time.':self.consentText};if(body.smsOptOut)next.smsOptIn=false;await store.setJSON('subscribers/'+key,next);return Response.json({saved:true},{headers});}
 if(['sms-code','sms-confirm'].includes(body.action)){
  if(!process.env.TWILIO_VERIFY_SERVICE_SID||!ready('sms'))fail('Connect Twilio SMS and TWILIO_VERIFY_SERVICE_SID to verify phone ownership.',503);if(body.confirm!==true)fail('Confirm that you want campaign texts.');const phone=String(body.phone||'');if(!/^\+[1-9]\d{7,14}$/.test(phone))fail('Use an international phone number, for example +14155550123.');
  const rate=`verification/${key}/${new Date().toISOString().slice(0,13)}`;if(body.action==='sms-code'){const r=await store.setJSON(rate,{at:new Date().toISOString()},{onlyIfNew:true});if(!r.modified)fail('A verification code was already requested this hour. Use that code or try again later.',429);}
  const base='https://verify.twilio.com/v2/Services/'+encodeURIComponent(process.env.TWILIO_VERIFY_SERVICE_SID),r=await fetch(base+(body.action==='sms-code'?'/Verifications':'/VerificationCheck'),{method:'POST',headers:{Authorization:'Basic '+Buffer.from(process.env.TWILIO_ACCOUNT_SID+':'+process.env.TWILIO_AUTH_TOKEN).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body.action==='sms-code'?{To:phone,Channel:'sms'}:{To:phone,Code:String(body.code||'')}),signal:AbortSignal.timeout(15000)}),d=await r.json();if(!r.ok)fail('Phone verification failed. Check the number and code.',400);if(body.action==='sms-confirm'){if(d.status!=='approved')fail('That code was not accepted.');await store.setJSON('subscribers/'+key,{...self,phone,smsOptIn:true,smsConsentedAt:new Date().toISOString(),smsConsentText:'I choose recurring campaign texts from this workspace. Message/data rates may apply. Reply STOP or use the unsubscribe link to stop.'});}return Response.json({status:d.status},{headers});
 }
 if(!admin)fail('Only an owner or editor can schedule campaigns.',403);
 if(body.action==='draft'){let campaign;try{campaign=validateCampaign(body)}catch(e){fail(e.message)}campaign={...campaign,workspace,author:user.id};await store.setJSON('campaigns/'+campaign.id,campaign,{onlyIfNew:true});return Response.json({campaign},{headers});}
 const campaign=await store.getWithMetadata('campaigns/'+id(body.id),{type:'json'});if(!campaign||campaign.data.workspace!==workspace)fail('Campaign unavailable.',404);const c=campaign.data;
 if(body.action==='schedule'){if(c.status!=='draft')fail('Only a draft can be scheduled.');if(body.confirm!==true)fail('Review the exact messages and confirm the schedule.');if(process.env.CAMPAIGN_DELIVERY_ENABLED!=='true'||!ready(c.channel))fail('Connect the sender service and enable campaign delivery before scheduling.',503);if(c.messages.some(m=>Date.parse(m.at)<=Date.now()))fail('A send time has passed. Create an updated draft.');c.status='scheduled';c.approvedBy=user.id;c.approvedAt=new Date().toISOString();}
 else if(body.action==='cancel'){c.status='canceled';c.canceledAt=new Date().toISOString();}
 else if(body.action==='results'){const entries=await store.list({prefix:'attempts/'+c.id+'/'}),results=[];for(const e of entries.blobs){const r=await store.get(e.key,{type:'json'});results.push({state:r.state,at:r.at,error:r.error})}return Response.json({results},{headers});}
 else fail('Unknown delivery action.',404);const result=await store.setJSON('campaigns/'+c.id,c,{onlyIfMatch:campaign.etag});if(!result.modified)fail('This schedule changed. Reload and try again.',409);return Response.json({campaign:c},{headers});
 }catch(e){return Response.json({error:e.status?e.message:'Delivery settings could not be updated. Please retry.'},{status:e.status||500,headers})}};
