import {inspectPDF} from '../pdf-inspection.mjs';
import {getUser,verifyRequestOrigin,refreshSession} from '@netlify/identity';import {getStore} from '@netlify/blobs';import {randomUUID,randomBytes,createHash} from 'node:crypto';import {PDFDocument} from 'pdf-lib';
const hash=v=>createHash('sha256').update(v).digest('hex'),ID=/^[a-zA-Z0-9-]{1,80}$/;
export default async request=>{const headers={'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'},store=getStore({name:'lifetogether-print-files-v1',consistency:'strong'});try{
 const url=new URL(request.url);if(request.method==='GET'&&url.searchParams.get('file')){const id=url.searchParams.get('file'),token=url.searchParams.get('token')||'';if(!ID.test(id))return new Response('Not found',{status:404,headers});const meta=await store.get('metadata/'+id,{type:'json'});if(!meta||meta.revoked||meta.expiresAt<new Date().toISOString()||meta.tokenHash!==hash(token))return new Response('File unavailable',{status:404,headers});const bytes=await store.get('files/'+id,{type:'arrayBuffer'});return new Response(bytes,{headers:{...headers,'Content-Type':'application/pdf','Content-Disposition':'inline; filename="lifetogether-'+meta.kind+'.pdf"'}})}
 if(request.method!=='POST')return Response.json({error:'Use POST.'},{status:405,headers});verifyRequestOrigin(request);await refreshSession();const user=await getUser();if(!user)return Response.json({error:'Sign in to save print files.'},{status:401,headers});const raw=await request.text();if(raw.length>4200000)return Response.json({error:'The PDF is too large. Use a file under 3 MB.'},{status:413,headers});const body=JSON.parse(raw);if(!ID.test(body.workspace||''))return Response.json({error:'Choose a workspace.'},{status:400,headers});const ws=await getStore({name:'lifetogether-platform-v1',consistency:'strong'}).get('workspaces/'+body.workspace,{type:'json'}),role=ws?.members[user.id]?.role;if(!['owner','editor'].includes(role))return Response.json({error:'Only workspace owners and editors can manage print files.'},{status:403,headers});
 if(body.action==='list'){const list=await store.list({prefix:'metadata/'}),files=[];for(const item of list.blobs){const m=await store.get(item.key,{type:'json'});if(m.workspace===body.workspace){const {tokenHash,...visible}=m;files.push(visible)}}return Response.json({files},{headers})}
 if(body.action==='revoke'){if(!ID.test(body.id||''))throw Error('Invalid file.');const meta=await store.get('metadata/'+body.id,{type:'json'});if(!meta||meta.workspace!==body.workspace)return Response.json({error:'File not found.'},{status:404,headers});await store.setJSON('metadata/'+body.id,{...meta,revoked:new Date().toISOString()});return Response.json({revoked:true},{headers})}
 if(body.action!=='upload'||!['interior','cover'].includes(body.kind)||body.confirm!==true)return Response.json({error:'Review and confirm the PDF before creating a printer-accessible link.'},{status:400,headers});const bytes=Buffer.from(body.pdf||'','base64');if(bytes.length>3000000||bytes.subarray(0,5).toString()!=='%PDF-')return Response.json({error:'Choose a valid PDF under 3 MB.'},{status:400,headers});let pdf;try{pdf=await PDFDocument.load(bytes)}catch{return Response.json({error:'The PDF could not be opened. Remove password protection and export it again.'},{status:400,headers})}if(body.kind==='cover'&&pdf.getPageCount()!==1)return Response.json({error:'A Lulu cover must be a single-page spread.'},{status:400,headers});const dimensions=pdf.getPages().map(p=>({width:p.getWidth()/72,height:p.getHeight()/72}));if(body.kind==='interior'&&dimensions.some(d=>Math.abs(d.width-dimensions[0].width)>.01||Math.abs(d.height-dimensions[0].height)>.01))return Response.json({error:'Every interior page must have the same dimensions.'},{status:400,headers});
 const preflight=await inspectPDF(bytes,{kind:body.kind,width:dimensions[0].width,height:dimensions[0].height});if(preflight.errors.length)return Response.json({error:preflight.errors.join(' ')},{status:400,headers});
 const id=randomUUID(),token=randomBytes(32).toString('base64url'),meta={id,workspace:body.workspace,kind:body.kind,title:String(body.title||'Print file').slice(0,200),pageCount:pdf.getPageCount(),dimensions:dimensions[0],createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+90*86400000).toISOString(),tokenHash:hash(token),owner:user.id,reviewer:user.id,reviewNote:String(body.reviewNote||'Reviewed upload confirmed').slice(0,500),preflight};await store.set('files/'+id,bytes);await store.setJSON('metadata/'+id,meta,{onlyIfNew:true});return Response.json({file:{...meta,tokenHash:undefined},url:url.origin+'/.netlify/functions/print-files?file='+id+'&token='+token},{headers});
 }catch{return Response.json({error:'The print file request could not be completed. Check the file and retry.'},{status:500,headers})}};
