'use strict';
const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[], requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 let configured=true, enabled=true, quoteFails=false, orderCount=0;
 await page.route('**/.netlify/functions/lulu?*',async route=>{
  const req=route.request(),action=new URL(req.url()).searchParams.get('action'),body=req.postDataJSON();requests.push({action,body});
  let data={},status=200;
  if(action==='connection')data={authenticated:true,environment:'sandbox',orders_enabled:enabled};
  if(action==='health')data={configured,environment:'sandbox',orders_enabled:enabled,contact_email_configured:false};
  if(action==='shipping-options')data=[{level:'GROUND_HD'},{level:'EXPRESS'}];
  if(action==='quote'){if(quoteFails){data={error:'Test: Lulu could not validate this address.'};status=400;}else data={currency:'USD',total_cost_incl_tax:'31.50',total_tax:'1.50',line_item_costs:[{total_cost_excl_tax:'20.00'}],shipping_cost:{total_cost_excl_tax:'8.00'},fulfillment_cost:{total_cost_excl_tax:'2.00'}};}
  if(action==='create-order'){orderCount++;await new Promise(r=>setTimeout(r,250));data={id:'test-order-1',status:{name:'CREATED'}};}
  if(action==='status')data={status:{name:'SHIPPED'},line_items:[{tracking_urls:['https://example.com/tracking','javascript:alert(1)']}]};
  await route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
 });
 const check=(name)=>console.log('PASS',name);
 await page.goto('http://127.0.0.1:8765/#/print-studio');
 await page.getByText('Connected to Lulu sandbox',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Prepare my first book →'}).click();
 await page.locator('#lulu-title').fill('Print studio test');
 await page.locator('#lulu-subtitle').fill('A book made for real people');
 await page.locator('#lulu-retail_price').fill('0');
 await page.getByRole('button',{name:'Save my book'}).click();
 await page.getByRole('heading',{name:'My books',exact:true}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'Print studio test',exact:true}).count(),1);check('Create a draft with preset format, no PDFs, and zero retail price');
 await page.getByRole('link',{name:'Edit book',exact:true}).click();
 assert.equal(await page.locator('#lulu-retail_price').inputValue(),'0.00');
 await page.locator('#lulu-format').selectOption('custom');assert.equal(await page.locator('#lulu-custom-format').isVisible(),true);
 await page.locator('#lulu-format').selectOption('paperback');
 await page.locator('#lulu-interior_url').fill('https://example.com/interior.pdf');
 await page.locator('#lulu-cover_url').fill('https://example.com/cover.pdf');
 await page.getByRole('button',{name:'Check links & open previews'}).click();
 assert.equal(await page.locator('#lulu-file-feedback a').count(),2);check('Custom format toggle and honest PDF link checks');
 await page.getByRole('button',{name:'Save my book'}).click();
 await page.getByRole('heading',{name:'My books',exact:true}).waitFor();
 let download=page.waitForEvent('download');await page.getByRole('button',{name:'Download details'}).click();assert.equal((await download).suggestedFilename(),'LifeTogether-print-edition.json');check('Download saved edition');
 await page.getByRole('link',{name:'Get a print estimate'}).click();
 for(const [name,value]of Object.entries({quantity:'2',name:'Test Recipient',street1:'123 Test Street',city:'Irvine',state_code:'CA',postcode:'92602',country_code:'US',phone_number:'+1 949 555 0100'}))await page.locator('#lulu-'+name).fill(value);
 await page.getByRole('button',{name:'Find delivery options'}).click();await page.getByText('2 delivery options found.',{exact:false}).waitFor();
 assert.equal(await page.locator('#lulu-street1').inputValue(),'123 Test Street');assert.equal(await page.locator('#lulu-shipping_option').inputValue(),'GROUND_HD');check('Shipping choices include residential ground and preserve the address');
 quoteFails=true;await page.getByRole('button',{name:'Calculate my estimate'}).click();await page.getByRole('alert').filter({hasText:'Test: Lulu'}).waitFor();assert.equal(await page.locator('#lulu-name').inputValue(),'Test Recipient');check('API errors visible without clearing fields');
 quoteFails=false;await page.getByRole('button',{name:'Calculate my estimate'}).click();await page.getByRole('heading',{name:'$31.50',exact:true}).waitFor();assert.equal(await page.locator('#lulu-name').inputValue(),'Test Recipient');
 download=page.waitForEvent('download');await page.getByRole('button',{name:'Download estimate'}).click();await download;check('Calculate and download estimate');
 await page.locator('#lulu-quantity').fill('3');assert.equal(await page.getByRole('button',{name:'Create test order'}).count(),0);check('Changing destination or quantity invalidates an old estimate');
 await page.getByRole('button',{name:'Calculate my estimate'}).click();await page.getByRole('button',{name:'Create test order'}).waitFor();
 await page.locator('#lulu-contact_email').fill('test@example.com');
 await page.getByRole('button',{name:'Create test order'}).dblclick();await page.getByText('Order test-order-1 created.',{exact:false}).waitFor();
 assert.equal(orderCount,1);const order=requests.find(x=>x.action==='create-order').body;assert.equal(order.line_item.quantity,3);assert.equal(order.shipping_address.street1,'123 Test Street');check('Only one order submitted, using the exact quoted address and quantity');
 await page.getByRole('button',{name:'Refresh status'}).click();await page.getByText('Order test-order-1: SHIPPED.',{exact:false}).waitFor();assert.equal(await page.getByRole('link',{name:'Track shipment 1 ↗'}).getAttribute('href'),'https://example.com/tracking');assert.equal(await page.locator('a[href^="javascript:"]').count(),0);check('Refresh order status and show safe tracking links');
 const storage=await page.evaluate(()=>localStorage.getItem('lifetogether-lulu-studio-v1'));assert(!storage.includes('123 Test Street'));assert(!storage.includes('Test Recipient'));check('Recipient details never saved in localStorage');
 configured=false;enabled=false;
 await page.getByRole('button',{name:'Check connection',exact:true}).first().click();await page.getByRole('button',{name:'Set up Lulu',exact:true}).waitFor();
 await page.getByRole('button',{name:'Set up Lulu',exact:true}).click();assert.equal(await page.locator('#lulu-setup').getAttribute('open'),'');
 download=page.waitForEvent('download');await page.getByRole('button',{name:'Download setup checklist'}).click();await download;check('Setup panel, recheck, and checklist work with missing credentials');
 await page.getByRole('link',{name:'Get a print estimate'}).click();await page.locator('#lulu-name').fill('Preserved draft');
 await page.getByRole('button',{name:'Find delivery options'}).click();await page.getByRole('alert').filter({hasText:'Connect Lulu'}).waitFor();assert.equal(await page.locator('#lulu-name').inputValue(),'Preserved draft');check('Unavailable live service has an actionable error');
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));check('Delivery form fits a mobile screen');
 await page.screenshot({path:'/private/tmp/lulu-mobile.png',fullPage:true});
 await page.goto('http://127.0.0.1:8765/#/print-studio');await page.getByRole('heading',{name:'My books',exact:true}).waitFor();
 await page.getByRole('button',{name:'Remove Print studio test'}).click();await page.getByRole('heading',{name:'No print editions yet.',exact:true}).waitFor();check('Remove book without deleting order history');
 assert.deepEqual(errors,[]);check('No JavaScript errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
