'use strict';
// Campaign planning is deterministic and local. Source material is never uploaded.
const LTCampaign = (() => {
  const schema = 'lifetogether-campaign-v1';
  const durations = [7, 10, 21, 30, 40, 60, 90];
  const layers = {pastor: 'Sermon intelligence', lifetogether: 'LifeTogether intelligence', church: 'Church intelligence'};
  const goals = {
    community: {label: 'Belonging & community', promise: 'build meaningful relationships, practice hospitality, and take a lasting step into community', terms: ['belong', 'community', 'together', 'hospitality', 'connection'], arc: ['Created for connection', 'Make room for one another', 'Listen with love', 'Carry one another’s burdens', 'Open the circle', 'Keep doing life together'], scripture: ['Acts 2:42–47', 'Romans 12:9–13', 'James 1:19–25', 'Galatians 6:2–10', 'Luke 14:12–24', 'Hebrews 10:23–25'], practice: ['Invite someone to share a meal and hear their story.', 'Make a specific invitation to someone outside your usual circle.', 'Listen without interrupting and reflect back what you heard.', 'Ask someone what burden you can help carry this week.', 'Welcome a neighbor or newcomer into an existing gathering.', 'Commit to a group and agree on your next meeting.']},
    formation: {label: 'Faith & spiritual formation', promise: 'develop sustainable rhythms of Scripture, prayer, obedience, and life with others', terms: ['faith', 'formation', 'prayer', 'discipleship', 'spiritual'], arc: ['Make space for God', 'Listen to the Word', 'Practice honest prayer', 'Take the next obedient step', 'Grow with others', 'Build a rhythm that lasts'], scripture: ['John 15:1–11', 'Psalm 119:9–16', 'Matthew 6:5–13', 'James 1:22–25', 'Colossians 3:12–17', 'Philippians 1:3–11'], practice: ['Set aside a repeatable time to be with God.', 'Read the passage slowly and write one response.', 'Pray honestly about one need and listen in silence.', 'Put one clear teaching into practice today.', 'Ask a trusted person to encourage your next step.', 'Choose a rhythm you will continue after the campaign.']},
    generosity: {label: 'Generosity & stewardship', promise: 'recognize God’s ownership, practice wise stewardship, and respond with thoughtful generosity', terms: ['generos', 'giving', 'steward', 'ownership'], arc: ['Receive life as a gift', 'Recognize God’s ownership', 'Notice what shapes your heart', 'Practice faithful stewardship', 'Give with a willing heart', 'Live generously together'], scripture: ['James 1:16–18', 'Psalm 24:1–6', 'Matthew 6:19–24', 'Luke 16:10–13', '2 Corinthians 9:6–12', '1 Timothy 6:17–19'], practice: ['Name three gifts you can steward in service of others.', 'Identify one area of life you tend to hold tightly.', 'Reflect on a recent decision and the priorities it revealed.', 'Discuss one wise next step with a trusted person.', 'Choose a freely given act of generosity within your means.', 'Make a sustainable plan for generosity and accountability.']},
    legacy: {label: 'Families & lasting legacy', promise: 'share faith and wisdom across generations and establish a meaningful family practice', terms: ['family', 'legacy', 'generation', 'parent', 'heir'], arc: ['Remember what matters', 'Tell the stories of faith', 'Listen across generations', 'Practice your values', 'Bless the next generation', 'Keep the conversation going'], scripture: ['Psalm 78:1–8', 'Deuteronomy 6:4–9', 'James 1:19–25', 'Joshua 24:14–15', 'Numbers 6:22–27', '2 Timothy 1:3–7'], practice: ['Name the values you hope those after you will remember.', 'Record a true story of faith with the storyteller’s consent.', 'Ask someone from another generation about their hopes.', 'Choose a shared action that expresses a family value.', 'Speak a specific encouragement to a younger person.', 'Schedule a recurring family conversation.']},
    leadership: {label: 'Purpose & leadership', promise: 'recognize their calling, serve with their gifts, and help another person grow', terms: ['purpose', 'leader', 'calling', 'vision', 'serve'], arc: ['Called to serve', 'Notice your gifts', 'Lead with character', 'Choose a faithful next step', 'Develop another person', 'Multiply faithful service'], scripture: ['Mark 10:35–45', 'Romans 12:3–8', '1 Timothy 3:1–13', 'Ephesians 2:8–10', '2 Timothy 2:1–7', '1 Peter 4:7–11'], practice: ['Serve in a way that brings no recognition.', 'Ask two people where they see you helping others.', 'Invite honest feedback about one leadership habit.', 'Choose a concrete opportunity to serve this week.', 'Encourage and equip someone else to take a next step.', 'Agree on a simple plan for continued mentoring.']},
    peace: {label: 'Hope & resilience', promise: 'bring their burdens to God, practice rest, and build supportive relationships', terms: ['peace', 'hope', 'anxiety', 'resilience', 'rest'], arc: ['Bring your whole story', 'Receive God’s care', 'Make room for rest', 'Choose the next faithful step', 'Let others walk with you', 'Practice hope together'], scripture: ['Psalm 13', '1 Peter 5:6–11', 'Matthew 11:28–30', 'Philippians 4:4–9', 'Romans 12:9–16', 'Romans 15:1–13'], practice: ['Name a burden honestly in prayer.', 'Identify one reminder of care you can return to.', 'Set a practical boundary that makes room for rest.', 'Take one manageable action with support.', 'Reach out to a trusted person and ask for company.', 'Choose a shared practice of hope you can sustain.']},
    mission: {label: 'Outreach & local mission', promise: 'notice their neighbors, share their faith naturally, and serve their community together', terms: ['mission', 'outreach', 'neighbor', 'evangel', 'community'], arc: ['See your neighborhood', 'Listen before you act', 'Offer genuine hospitality', 'Serve a real need', 'Share your story', 'Stay present together'], scripture: ['Luke 10:25–37', 'James 1:19–27', 'Luke 19:1–10', 'Matthew 5:13–16', '1 Peter 3:13–17', 'Matthew 28:16–20'], practice: ['Pray for and learn the name of a neighbor.', 'Ask a local partner what would truly help.', 'Invite someone into a simple shared meal.', 'Serve alongside a community partner.', 'Practice telling your faith story with humility.', 'Commit to an ongoing relationship of service.']},
    scripture: {label: 'Life & teaching of Jesus', promise: 'understand Jesus’ teaching in context and put a specific teaching into practice', terms: ['jesus', 'christ', 'gospel', 'scripture', 'red letter'], arc: ['Come and see', 'Hear the good news', 'Learn the way of Jesus', 'Practice mercy', 'Follow through the cost', 'Go and make disciples'], scripture: ['John 1:35–51', 'Mark 1:14–20', 'Matthew 5:1–12', 'Luke 10:25–37', 'Luke 9:18–27', 'Matthew 28:16–20'], practice: ['Read the passage and name what you notice about Jesus.', 'Consider where Jesus’ invitation meets your life.', 'Choose one teaching to practice this week.', 'Offer a concrete act of mercy.', 'Discuss a difficult next step with a trusted friend.', 'Invite someone to continue learning and practicing with you.']}
  };
  const components = [
    ['sermons', 'Weekend sermons', 'A teaching brief for every week', true, 'Preaching'],
    ['groups', 'Small groups', 'Discussion, practice, prayer, and leader notes', true, 'Groups'],
    ['daily', 'Daily devotion & practice', 'Every day connected to the weekly message', true, 'Discipleship'],
    ['family', 'Family conversations', 'A weekly practice for the whole household', true, 'Family'],
    ['children', 'Children’s edition', 'Age-appropriate teaching and caregiver connection', false, 'Children'],
    ['youth', 'Youth edition', 'Honest conversation and a concrete student challenge', false, 'Youth'],
    ['hosts', 'Host recruitment & training', 'Recruit, prepare, and care for group hosts', true, 'Groups'],
    ['prayer', 'Prayer guide', 'A shared rhythm for the church and leadership', true, 'Prayer'],
    ['testimony', 'Testimony story kit', 'Gather true stories with consent', true, 'Stories'],
    ['email', 'Email & text invitations', 'Launch, weekly encouragement, and follow-through', true, 'Communications'],
    ['social', 'Social content', 'Weekly invitations and practical prompts', false, 'Communications'],
    ['video', 'Teaching video briefs', 'One production brief per week', false, 'Production'],
    ['landing', 'Campaign landing page copy', 'An invitation, weekly rhythm, and clear next step', false, 'Communications'],
    ['branding', 'Design & print brief', 'Visual direction and a deliverable checklist', false, 'Production'],
    ['assessment', 'Entry & exit reflection', 'Measure participation and changed practices', true, 'Discipleship'],
    ['next', 'Next-step pathway', 'Keep groups, practices, and mission moving', true, 'Discipleship'],
    ['generosity', 'Generosity initiative', 'A voluntary invitation with a clear ministry purpose', false, 'Leadership']
  ].map(([id, label, description, included, owner]) => ({id, label, description, included, owner}));
  const phases = [
    {id:'decide', label:'Decide', offset:-56, description:'Align the vision and choose the people and sources.'},
    {id:'build', label:'Build', offset:-42, description:'Shape the teaching, practices, and campaign resources.'},
    {id:'recruit', label:'Recruit', offset:-28, description:'Invite champions and prepare group hosts.'},
    {id:'prime', label:'Prime', offset:-14, description:'Prepare the church and make the invitation clear.'},
    {id:'run', label:'Run', offset:0, description:'Teach, practice, care for people, and listen to stories.'},
    {id:'land', label:'Land', offset:null, description:'Celebrate, learn, and launch the next faithful step.'}
  ];
  const id = () => 'CP-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2,8);
  const copy = value => JSON.parse(JSON.stringify(value));
  const clean = (value, max=2000) => String(value ?? '').replace(/\u0000/g,'').slice(0,max);
  const number = (value, min=0, max=1000000) => Math.min(max,Math.max(min,Number(value)||0));
  const norm = value => clean(value).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const safeURL = value => {try {const u=new URL(value);return /^https?:$/.test(u.protocol)?u.href:'';} catch {return '';}};
  function date(value, offset=0) {
    if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return '';
    const d=new Date(value+'T12:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==value)return '';
    d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10);
  }
  const weekCount = c => Math.ceil(c.profile.duration/7);
  function create(seed={}) {
    return {schema,id:id(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),title:'',subtitle:'',step:0,
      profile:{church:'',pastor:'',goal:'community',objective:'',audience:'Whole church',context:'',mission:'',theology:'',voice:'Warm, biblical, conversational, and practical',translation:'NIV',duration:40,launchDate:'',sermonMinutes:30,groupMinutes:60,devotionalMinutes:10,attendance:0,participation:60,groupSize:10,existingGroups:0,printBuffer:10,champions:'',catalytic:'',distribution:'Weekend gatherings, small groups, and daily email',stories:'',multiplication:'',nextStep:'',...seed},
      sources:[],scope:Object.fromEntries(components.map(x=>[x.id,x.included?'now':'later'])),weeks:[],assets:{},tasks:{},measures:{participants:'',groups:'',hosts:'',stories:'',nextSteps:'',baseline:'',reflection:''},review:{pastor:'',date:'',approved:false},example:false};
  }
  function source(raw) {
    const layer=Object.hasOwn(layers,raw.layer)?raw.layer:'pastor';
    return {id:clean(raw.id||id(),100),layer,title:clean(raw.title,250),subtitle:clean(raw.subtitle,600),speaker:clean(raw.speaker,200),church:clean(raw.church,200),series:clean(raw.series,250),date:date(raw.date),scripture:clean(raw.scripture,400),url:safeURL(raw.url),locator:clean(raw.locator,400),notes:clean(raw.notes,60000),bigIdea:clean(raw.bigIdea,1200),practice:clean(raw.practice,1200),permission:['owned','authorized','internal','reference','restricted'].includes(raw.permission)?raw.permission:layer==='pastor'?'internal':'reference',recordId:clean(raw.recordId,100),kind:clean(raw.kind||'notes',50),selected:raw.selected!==false,complete:raw.complete===true,catalogRestricted:raw.catalogRestricted===true};
  }
  function denied(r) {return /^yes/i.test(r['Do Not Send to AI Yet?']||'')||/do not build|removed|park for later|deferred/i.test([r['Build Decision'],r['Source Item Type'],r.Notes].join(' '));}
  function catalogLayer(r) {
    if(r['Priority Grade']==='REFERENCE'||/market benchmark|third.party/i.test([r.Category,r['Source Item Type']].join(' ')))return r._section!==1||/removed|park for later|deferred/i.test([r['Build Decision'],r.Notes].join(' '))?'':'church';
    if(denied(r))return '';
    if(r._section===1||r._memory)return 'lifetogether';
    return '';
  }
  function fromRecord(r) {return source({id:'SRC-'+r['Master ID'],recordId:r['Master ID'],layer:catalogLayer(r),title:r['Campaign Title'],subtitle:r.Subtitle,kind:r._memory?'recovered concept':'catalog reference',permission:'reference',notes:'',scripture:'',locator:r['Master ID'],catalogRestricted:denied(r)});}
  function searchCatalog(records, layer, query, goal) {
    const terms=norm(query).split(' ').filter(Boolean),theme=goals[goal]||goals.community;
    return records.filter(r=>catalogLayer(r)===layer).map(r=>{const t=norm([r['Campaign Title'],r.Subtitle,r.Category,r['Best For / Audience']].join(' '));return {r,match:terms.every(w=>t.includes(w)),score:theme.terms.reduce((s,w)=>s+(t.includes(w)?3:0),0)+(r['Priority Grade']==='AA'?2:0)};}).filter(x=>x.match).sort((a,b)=>b.score-a.score||String(a.r['Campaign Title']).localeCompare(String(b.r['Campaign Title'])));
  }
  function selected(c) {return c.sources.filter(s=>s.selected&&s.permission!=='restricted');}
  function teachingSources(c) {return selected(c).filter(s=>!s.catalogRestricted&&(s.layer!=='church'||['owned','authorized'].includes(s.permission)));}
  function extracted(s) {
    const lines=s.notes.split(/\n+/).map(x=>x.trim()).filter(Boolean);
    const find=labels=>{const line=lines.find(x=>new RegExp('^(?:'+labels+')\\s*[:—-]','i').test(x));return line?line.replace(/^[^:—-]+[:—-]\s*/,''):'';};
    return {bigIdea:s.bigIdea||find('big idea|main idea|central truth|theme'),practice:s.practice||find('practice|application|next step|challenge'),scripture:s.scripture||find('scripture|passage|text'),excerpt:lines.filter(x=>!/^#|^(title|subtitle|speaker|church|date|series)\s*:/i.test(x)).join(' ').slice(0,420)};
  }
  function syncWeeks(c) {
    const g=goals[c.profile.goal]||goals.community,ss=teachingSources(c),n=weekCount(c);
    const basis=JSON.stringify([c.profile.goal,c.profile.duration,c.profile.objective,ss.map(s=>[s.id,extracted(s)])]);
    if(c.planBasis!==basis){
      const old=c.weeks;
      c.weeks=Array.from({length:Math.max(n,old.length)},(_,i)=>{
        if(old[i]?.edited||old[i]?.reviewed||i>=n)return old[i];
        const a=Math.min(5,Math.floor(i*6/n)),s=ss[i%Math.max(1,ss.length)],x=s?extracted(s):{};
        return {number:i+1,title:g.arc[a],bigIdea:x.bigIdea||g.arc[a]+': '+(c.profile.objective||g.promise)+'.',scripture:x.scripture||g.scripture[a],scriptureSuggested:!x.scripture,practice:x.practice||g.practice[a],sourceIds:s?[s.id]:[],groupQuestion:'Where does this teaching meet a real situation in your life?',familyPractice:'Share a story from your week, listen to each person, and choose one way to practice this together.',reviewed:false,edited:false};
      });
      c.planBasis=basis;
    }
    return c.weeks.slice(0,n);
  }
  function capacity(c) {const p=c.profile,participants=Math.ceil(number(p.attendance)*number(p.participation,0,100)/100),groups=Math.ceil(participants/number(p.groupSize,1,100));return {participants,groups,newHosts:Math.max(0,groups-number(p.existingGroups)),copies:Math.ceil(participants*(1+number(p.printBuffer,0,100)/100))};}
  function days(c) {return Array.from({length:c.profile.duration},(_,i)=>({number:i+1,week:Math.floor(i/7)+1,kind:i%7===0?'Gather & reflect':'Read & practice',date:date(c.profile.launchDate,i),rhythm:i%7}));}
  const once=new Set(['hosts','prayer','testimony','landing','branding','assessment','next','generosity']);
  function descriptors(c) {
    const out=[],ww=syncWeeks(c);for(const comp of components.filter(x=>c.scope[x.id]==='now')){
      if(comp.id==='daily'){for(const d of days(c))out.push({id:'daily-'+d.number,type:'daily',label:'Day '+d.number+' · '+d.kind,week:d.week,day:d.number,offset:d.number-1,owner:comp.owner});}
      else if(once.has(comp.id))out.push({id:comp.id,type:comp.id,label:comp.label,week:1,offset:comp.id==='next'?c.profile.duration:comp.id==='hosts'?-28:comp.id==='landing'?-14:comp.id==='branding'?-21:0,owner:comp.owner});
      else for(const w of ww)out.push({id:comp.id+'-'+w.number,type:comp.id,label:'Week '+w.number+' · '+comp.label,week:w.number,offset:(w.number-1)*7,owner:comp.owner});
    }return out;
  }
  function draft(c,d) {
    const w=syncWeeks(c)[d.week-1],name=c.title||'Your campaign',p=c.profile,theme=goals[p.goal]||goals.community,objective=p.objective||theme.promise,ss=w.sourceIds.map(id=>teachingSources(c).find(s=>s.id===id)).filter(Boolean),sourceNotes=ss.map(s=>{const x=extracted(s);return s.title+(s.speaker?' — '+s.speaker:'')+(x.bigIdea?'\nRecorded big idea: '+x.bigIdea:'')+(x.excerpt&&!x.bigIdea&&s.layer==='pastor'?'\nWorking excerpt from your notes: '+x.excerpt:'');}).join('\n\n');
    const intro=`${name}\n${d.label}: ${w.title}\n\nTransformation goal\n${objective}\n\nScripture to read in context\n${w.scripture} (${p.translation})${w.scriptureSuggested?' — suggested reference; confirm the fit with your teaching.':''}\n\nTeaching focus\n${w.bigIdea}\n\nLocal context to address\n${p.context||'Add the needs and opportunities in your church.'}\n`;
    const group=`\nWelcome & reconnect (10 minutes)\nInvite each person to share one moment from the week. Ask what happened when they tried the previous practice. Let people pass when they need to.\n\nRead & notice (10 minutes)\nRead ${w.scripture} together. What does the passage say in its original setting? What do you notice about God, people, and the invitation to respond?\n\nDiscuss & apply (${Math.max(10,p.groupMinutes-30)} minutes)\n1. ${w.groupQuestion}\n2. What assumption or habit does this passage invite you to examine?\n3. How does the teaching connect with the needs in your church and community?\n4. What would a faithful, practical response look like this week?\n\nPractice & pray (10 minutes)\n${w.practice} Ask each person to name one next step and one person who can encourage them. Pray for one another without pressuring anyone to disclose more than they wish.\n\nLeader preparation\nRead the full passage and your pastor’s message. Keep the discussion grounded in the text. Make space for quieter voices and agree on a follow-up before you finish.`;
    let body='';
    switch(d.type){
      case 'sermons':body=`\nOpening: connect with real life\nBegin with an authentic observation from your local church. Invite people to consider why this matters in ordinary life. Add a true story from your own experience; no testimony has been invented for this draft.\n\nBiblical exposition\nRead ${w.scripture} in context. Explain the setting, the central claim, and how the passage supports the teaching focus. Preserve your own theological convictions${p.theology?': '+p.theology:''}. Distinguish what the text says from your contemporary application.\n\nMovement 1 · Name the invitation\nDevelop the central truth: ${w.bigIdea} Connect it to the congregation’s transformation goal.\n\nMovement 2 · Explore the resistance\nName a common obstacle in your local context. Return to the passage and explain how it addresses that obstacle. Insert a source-supported illustration from your library.\n\nMovement 3 · Practice together\n${w.practice} Describe a small, specific step people can take, and connect it to this week’s group conversation and daily rhythm.\n\nResponse & prayer\nInvite an unhurried response. Explain the next practical opportunity to participate: ${p.distribution}. Close with prayer rooted in the passage.\n\nPreparation notes\nTarget: ${p.sermonMinutes} minutes. Voice: ${p.voice}. This is an editable teaching outline; develop and review the exposition before preaching.`;break;
      case 'groups':body=group;break;
      case 'daily':{const dInfo=days(c)[d.day-1],rhythms=['Gather and receive','Notice the passage','Reflect honestly','Take a first step','Practice with another person','Share what you are learning','Rest and remember'],r=dInfo.rhythm;body=`\nDay ${d.day} · ${rhythms[r]}\nSet aside about ${p.devotionalMinutes} minutes. ${r===0?'After the gathering, return to the passage and write down one teaching you want to carry into the week.':'Read the passage slowly. Notice a word, action, or question that helps you pay attention to the weekly teaching.'}\n\nReflection\nThis week’s focus is ${w.title.toLowerCase()}. Consider how it connects to your actual relationships, responsibilities, and decisions. Use your pastor’s teaching to explore ${w.bigIdea.charAt(0).toLowerCase()+w.bigIdea.slice(1)} Leave room for honest questions as you respond to God.\n\nStory to add\nAdd a true, permission-cleared story from the selected teaching that illustrates today’s focus. Until that story is supplied, this remains an editorial draft.\n\nPractice\n${r===0?'Write one next step from the message and share it with someone you trust.':r===2?'Write about one situation where this practice feels difficult, then ask God for wisdom.':r===4?'Invite a trusted person to practice with you and agree on a time to check in.':r===6?'Review what you noticed this week. Thank God for one change and make room for rest.':w.practice}\n\nThree reflection questions\n1. What does the passage help me see more clearly?\n2. Where does this meet my life today?\n3. What specific response can I take, and who can encourage me?\n\nPrayer & next step\nPray in your own words about what you noticed. ${r===6?'Bring one observation or question into the next gathering.':'Return to this practice tomorrow and notice what changes.'}`;break;}
      case 'family':body=`\nAround the table\n${w.familyPractice}\n\nRead & wonder\nRead the passage in an age-appropriate way. Ask: What do you notice? What is one question you have? Adults can model honest reflection without expecting polished answers.\n\nPractice as a household\n${w.practice} Adapt the action so each person can participate. Choose a time to reconnect and hear what happened.\n\nBlessing\nInvite each person to name one reason they are thankful for another. Pray briefly for the coming week. Keep participation welcoming for single adults, blended families, and households at different stages of faith.`;break;
      case 'children':body=`\nLeader preparation\nChoose an age group and read the passage before adapting it. Use concrete language and one central idea. Coordinate the lesson with the church’s safeguarding and check-in practices.\n\nWelcome & discover\nInvite children to describe a familiar situation connected to ${w.title.toLowerCase()}. Retell the biblical account accurately in your own words, without adding invented details.\n\nActivity\nCreate a simple drawing or role-play that helps children notice the weekly practice: ${w.practice}\n\nTalk & pray\nAsk what they noticed about God and what one kind or faithful action could look like this week. Give caregivers a short recap and one conversation question.`;break;
      case 'youth':body=`\nStart with their world\nInvite students to name a real pressure connected to ${w.title.toLowerCase()}. Allow honest questions and avoid requiring personal disclosure.\n\nRead & discuss\nRead the passage in context. Ask what stands out, what feels challenging, and where the teaching intersects with friendships, school, work, or home.\n\nChallenge\n${w.practice} Let students choose a concrete version they can practice safely this week.\n\nFollow-through\nAsk students how they want to encourage one another. End with a brief prayer and a reminder of how to reach a trusted ministry leader.`;break;
      case 'hosts':body=`\nRecruitment invitation\nWe are preparing ${name} so people can grow through Scripture, honest conversation, and shared practice. A host makes room, welcomes people, helps the group stay connected, and asks for help when it is needed. Invite prospective hosts to a conversation about this role.\n\nTraining agenda\n1. Share the transformation goal and weekly rhythm.\n2. Model a short group conversation using the first session.\n3. Practice asking open questions and welcoming quieter voices.\n4. Explain prayer, care boundaries, and the pastoral escalation contact.\n5. Confirm meeting time, accessibility, childcare arrangements, and follow-up.\n\nWeekly coaching\nCheck in before the first meeting, after week one, and midway through the campaign. Ask about attendance, relationships, support needs, and stories. End by helping the host plan the group’s next step.\n\nChurch contacts to supply\nGroups coordinator, pastoral care contact, safeguarding contact, and a backup host.`;break;
      case 'prayer':body=`\nBefore launch\nPray with the campaign team for openness to Scripture, unity, and attentive care for people. Invite the church to pray for specific relationships and ministry opportunities.\n\nDuring the campaign\nUse the weekly passage as the starting point for prayer. Give thanks, name needs honestly, and pray for the week’s practice. Invite groups and households to join this rhythm in their own words.\n\nAfter the campaign\nGive thanks for what people actually experienced. Pray for the commitments, continuing groups, and ministry steps named during the celebration.`;break;
      case 'testimony':body=`\nInvite a true story\nAsk: What was happening before the campaign? Which teaching or practice mattered to you? What action did you take? What changed, and what is still unfinished?\n\nCapture with care\nRecord the storyteller’s own words. Confirm their permission, preferred name, audience, and comfort with recording or publication. Avoid implying that every participant experienced the same result.\n\nPrepare for sharing\nKeep the story focused on a concrete experience. Let the storyteller review edits. Confirm consent again before any public use.\n\nStory record\nStoryteller · interviewer · date · source session · sharing permission · review date · final approved version.`;break;
      case 'email':body=`\nSubject: ${w.title} — this week in ${name}\n\nHello church family,\n\nThis week we are exploring ${w.title.toLowerCase()} as part of ${name}. Our hope is that together we will ${objective.replace(/^By the end[^,]*,\s*/i,'')}.\n\nRead ${w.scripture} and bring your questions to the gathering. In your group or household, talk about one way the teaching meets your everyday life. This week’s practical invitation is simple: ${w.practice}\n\n${p.nextStep||'Connect with the church team to find a group and take part in this week’s rhythm.'}\n\nWith you,\n${p.pastor||'Your church team'}\n\nShort text message\nThis week in ${name}: ${w.title}. Read ${w.scripture}, try the weekly practice, and share what you notice with your group. Add your church’s meeting or sign-up link before sending.`;break;
      case 'social':body=`\nPost 1 · Invitation\nThere is room for you in ${name}. This week: ${w.title}. Join us as we explore ${w.scripture} and take a practical step together. Add gathering details and an accessible sign-up link.\n\nPost 2 · Practice\nTry this with us: ${w.practice} Share an observation with someone you trust.\n\nPost 3 · Reflection\nWhat are you noticing as we practice together? Bring one question or story to your group this week.\n\nVisual direction\nUse real, consented church photography, readable text, alt text, and your church’s approved brand.`;break;
      case 'video':body=`\nVideo teaching brief\nSpeaker: ${p.pastor||'Assign the teaching pastor'}. Open with the weekly question, read the passage in context, explain the big idea, and invite the practice.\n\nSuggested sequence\nWelcome and local connection → Scripture → one developed teaching movement → source-supported illustration → group discussion handoff.\n\nProduction checklist\nConfirm script and source review, location, sound, lighting, captions, framing, and final pastoral approval. Record the speaker in their own voice.`;break;
      case 'landing':body=`\nPage headline\n${name}\n\nSubheadline\n${c.subtitle||'A churchwide invitation to '+theme.promise+'.'}\n\nWhy take part\nWe are setting aside ${p.duration} days to grow together around one shared goal: ${objective}. You can participate through the weekend gathering, a group, and a manageable daily practice.\n\nWhat to expect\nA weekly teaching, space for honest conversation, and a practical way to respond. ${p.launchDate?'We begin '+p.launchDate+'.':'Add the confirmed launch date.'}\n\nYour next step\n${p.nextStep||'Find a group or contact the church team to get started.'}\n\nDetails to add before publication\nGathering times, group sign-up link, accessibility and childcare information, contact person, and resource delivery instructions.`;break;
      case 'branding':body=`\nCreative direction\nExpress ${theme.label.toLowerCase()} with a clear title, generous space, and people-centered imagery. Apply the church’s existing logo, type, and colors.\n\nDeliverables\nCampaign key art; sermon screen; group guide cover; daily resource cover; social invitation; email header; print sign-up card.\n\nProduction details\nConfirm print sizes, quantity, bleed, delivery date, accessible contrast, captions and alt text, and rights for every image. Keep dates, links, and contact details consistent across formats.`;break;
      case 'assessment':body=`\nEntry reflection\nBefore launch, ask participants to reflect on their current practice related to ${theme.label.toLowerCase()}. Use a consistent scale from 1 (rarely) to 5 (consistently).\n\nRepeat at entry and exit\n1. I can describe how Scripture shapes this area of my life.\n2. I practice a specific response during an ordinary week.\n3. I have someone who encourages me in this area.\n\nOpen questions\nWhat do you hope to learn or practice? At the end: what did you try, what changed, and what support would help you continue?\n\nUse the results\nCompare like-for-like responses when consent and collection methods allow. Report participation and actual responses without claiming the campaign caused every change. Record anonymous themes and concrete next steps.`;break;
      case 'next':body=`\nCelebrate what happened\nShare true, reviewed stories and the participation figures the team actually recorded. Thank hosts, volunteers, and participants.\n\nMake the next step clear\n${p.nextStep||'Invite each group to choose its next meeting and each participant to continue one practice.'}\n\nWithin two weeks\nContact hosts, offer pastoral follow-up where requested, and confirm continuing groups and ministry opportunities.\n\nAt 30 days\nAsk which practices and relationships continued. Use those observations to refine the next campaign and support new leaders.\n\nMultiplication plan\n${p.multiplication||'Invite emerging hosts to shadow an experienced leader and prepare a next group or ministry step.'}`;break;
      case 'generosity':body=`\nMinistry purpose\nDescribe the specific ministry opportunity, who it serves, and how contributions will be stewarded. Add only financial details that the church has approved.\n\nInvitation\nInvite thoughtful, voluntary participation in response to Scripture. Include prayer, service, time, and generosity as possible responses. Avoid pressure or promises of personal financial return.\n\nAccountability\nName the responsible church leader, communication plan, and how the church will report actual use and outcomes. Connect the initiative to the campaign’s wider transformation goal.`;break;
    }
    return intro+body+'\n\nSource and editorial notes\n'+(sourceNotes||'No teaching notes are attached to this week. Add your sermon source before treating this as source-derived teaching.')+'\n\nThis is an editorial planning draft. Suggested structure, questions, and applications require your review; they are not attributed to a source author. Global references with unconfirmed rights are used for planning context only.';
  }
  function fingerprint(c,d){let h=2166136261;for(const ch of draft(c,d)){h^=ch.codePointAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(16);}
  function buildAssets(c) {for(const d of descriptors(c))if(!c.assets[d.id])c.assets[d.id]={body:draft(c,d),signature:fingerprint(c,d),status:'draft',owner:'',reviewer:'',edited:false,createdAt:new Date().toISOString()};return c.assets;}
  function launchTasks(c) {
    const definitions=[['vision','decide',-56,'Agree on the transformation goal','Leadership',''],['sources','decide',-49,'Select teaching sources and confirm intended use','Preaching',''],['scope','decide',-49,'Confirm the campaign scope and team','Leadership',''],['teaching','build',-35,'Review the weekly teaching arc','Preaching','sermons'],['group-guides','build',-28,'Finish group guides and leader notes','Groups','groups'],['daily-guides','build',-21,'Review daily readings and delivery','Discipleship','daily'],['editions','build',-21,'Coordinate family, children, and youth plans','Family','family'],['design','build',-21,'Approve design and send print files','Production','branding'],['champions','recruit',-28,'Invite campaign champions','Leadership',''],['hosts','recruit',-28,'Recruit and confirm group hosts','Groups','hosts'],['train','recruit',-14,'Train hosts and assign coaches','Groups','hosts'],['invite','prime',-14,'Open invitations and group registration','Communications',''],['prayer','prime',-7,'Gather the team for prayer','Prayer','prayer'],['test','prime',-7,'Test every link, room, and resource delivery','Operations',''],['launch','run',0,'Launch the campaign and invite a response','Preaching',''],['care','run',7,'Check in with hosts and participants','Groups','groups'],['midpoint','run',Math.floor(c.profile.duration/2),'Review participation and remove obstacles','Leadership',''],['stories','run',Math.max(0,c.profile.duration-10),'Collect and review participant stories','Stories','testimony'],['celebrate','land',c.profile.duration,'Celebrate and invite the next step','Leadership',''],['follow-up','land',c.profile.duration+14,'Follow up with groups and ministry leaders','Discipleship','next'],['learn','land',c.profile.duration+30,'Review what continued and what to improve','Leadership','']];
    return definitions.filter(x=>!x[5]||c.scope[x[5]]==='now').map(([id,phase,offset,title,role])=>({id,phase,offset,title,role,date:date(c.profile.launchDate,offset),owner:c.tasks[id]?.owner||'',done:c.tasks[id]?.done||false}));
  }
  function readiness(c) {
    const ww=syncWeeks(c),dd=descriptors(c),ss=selected(c),tt=launchTasks(c);
    return [
      {id:'vision',label:'A clear title and transformation goal',done:!!(c.title.trim()&&c.profile.objective.trim()),step:0},
      {id:'sources',label:'Teaching sources attached to every week',done:ww.every(w=>w.sourceIds.some(id=>teachingSources(c).some(s=>s.id===id&&(s.notes.trim()||s.bigIdea.trim())))),step:3},
      {id:'permissions',label:'Selected sources cleared for the intended use',done:ss.length>0&&ss.every(s=>!s.catalogRestricted&&['owned','authorized'].includes(s.permission)),step:1},
      {id:'arc',label:'Every weekly teaching plan reviewed',done:ww.length>0&&ww.every(w=>w.reviewed&&w.title&&w.bigIdea&&w.scripture),step:3},
      {id:'resources',label:'All included resource drafts reviewed',done:dd.length>0&&dd.every(d=>c.assets[d.id]?.status==='reviewed'&&c.assets[d.id]?.body.trim()&&c.assets[d.id]?.signature===fingerprint(c,d)),step:4},
      {id:'team',label:'Launch date and task owners assigned',done:!!c.profile.launchDate&&tt.every(t=>t.owner.trim()),step:5},
      {id:'next',label:'A next step beyond the campaign',done:!!c.profile.nextStep.trim(),step:0},
      {id:'approval',label:'Final pastoral review recorded',done:!!(c.review.approved&&c.review.pastor.trim()&&c.review.date),step:6}
    ];
  }
  function importCampaign(raw) {
    if(!raw||raw.schema!==schema||!raw.profile||!Array.isArray(raw.sources)||!Array.isArray(raw.weeks))throw Error('Choose a LifeTogether campaign backup file.');
    if(raw.sources.length>200||raw.weeks.length>13||Object.keys(raw.assets||{}).length>1000)throw Error('This campaign is larger than the supported workspace.');
    const c=create();c.title=clean(raw.title,180);c.subtitle=clean(raw.subtitle,600);c.step=number(raw.step,0,6);c.example=raw.example===true;
    for(const key of Object.keys(c.profile))if(raw.profile[key]!==undefined)c.profile[key]=typeof c.profile[key]==='number'?number(raw.profile[key]):clean(raw.profile[key],4000);
    c.profile.goal=Object.hasOwn(goals,c.profile.goal)?c.profile.goal:'community';c.profile.duration=durations.includes(Number(c.profile.duration))?Number(c.profile.duration):40;c.profile.launchDate=date(c.profile.launchDate);c.profile.groupSize=number(c.profile.groupSize,1,100);c.profile.participation=number(c.profile.participation,0,100);
    c.sources=raw.sources.map(source);if(new Set(c.sources.map(s=>s.id)).size!==c.sources.length)throw Error('The campaign has duplicate source IDs.');
    for(const key of Object.keys(c.scope))if(['now','later','off'].includes(raw.scope?.[key]))c.scope[key]=raw.scope[key];
    c.weeks=raw.weeks.map((w,i)=>({number:i+1,title:clean(w.title,250),bigIdea:clean(w.bigIdea,1800),scripture:clean(w.scripture,400),scriptureSuggested:!!w.scriptureSuggested,practice:clean(w.practice,1600),sourceIds:Array.isArray(w.sourceIds)?w.sourceIds.filter(id=>c.sources.some(s=>s.id===id)):[],groupQuestion:clean(w.groupQuestion,1000),familyPractice:clean(w.familyPractice,1600),reviewed:w.reviewed===true,edited:w.edited===true}));
    for(const [key,value] of Object.entries(raw.assets||{})){if(!/^[a-z]+(?:-\d+)?$/.test(key))continue;c.assets[key]={body:clean(value.body,60000),signature:clean(value.signature,100),owner:clean(value.owner,200),reviewer:clean(value.reviewer,200),status:['draft','review','reviewed'].includes(value.status)?value.status:'draft',edited:!!value.edited,createdAt:clean(value.createdAt,50)};}
    for(const [key,value] of Object.entries(raw.tasks||{}))if(/^[a-z-]+$/.test(key))c.tasks[key]={owner:clean(value.owner,200),done:value.done===true};
    for(const key of Object.keys(c.measures))c.measures[key]=clean(raw.measures?.[key],3000);
    c.review={pastor:clean(raw.review?.pastor,200),date:date(raw.review?.date),approved:raw.review?.approved===true};c.planBasis=JSON.stringify([c.profile.goal,c.profile.duration,c.profile.objective,teachingSources(c).map(s=>[s.id,extracted(s)])]);return c;
  }
  async function docxXML(bytes) {
    const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let end=-1;
    for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){end=i;break;}
    if(end<0)throw Error('This Word file could not be read. Save it as .docx or paste the text.');
    let pos=v.getUint32(end+16,true),count=v.getUint16(end+10,true);
    for(let n=0;n<count;n++){
      if(pos+46>bytes.length||v.getUint32(pos,true)!==0x02014b50)throw Error('The Word document archive is damaged.');
      const method=v.getUint16(pos+10,true),compressed=v.getUint32(pos+20,true),size=v.getUint32(pos+24,true),nameLen=v.getUint16(pos+28,true),extra=v.getUint16(pos+30,true),comment=v.getUint16(pos+32,true),offset=v.getUint32(pos+42,true),name=new TextDecoder().decode(bytes.slice(pos+46,pos+46+nameLen));
      if(name==='word/document.xml'){
        if(size>3000000||offset+30>bytes.length)throw Error('This Word document is too large or damaged. Split it into individual sermons.');
        const start=offset+30+v.getUint16(offset+26,true)+v.getUint16(offset+28,true);if(start+compressed>bytes.length)throw Error('The Word document archive is incomplete.');
        const data=bytes.slice(start,start+compressed);if(method===0)return new TextDecoder().decode(data);
        if(method!==8)throw Error('Unsupported Word compression. Export the document as text.');
        const reader=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader(),chunks=[];let length=0;
        for(;;){const chunk=await reader.read();if(chunk.done)break;length+=chunk.value.length;if(length>3000000){await reader.cancel();throw Error('The expanded Word document is too large.');}chunks.push(chunk.value);}
        const plain=new Uint8Array(length);let at=0;for(const chunk of chunks){plain.set(chunk,at);at+=chunk.length;}return new TextDecoder().decode(plain);
      }
      pos+=46+nameLen+extra+comment;
    }
    throw Error('No document text found. Export the file as text.');
  }
  function parseCSV(text) {
    const rows=[];let row=[],cell='',quote=false;
    for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(ch===','&&!quote){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=ch;}
    if(quote)throw Error('The CSV contains an unclosed quoted field.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;
  }
  function importSources(text,filename,layer='pastor') {
    let items;
    if(/\.json$/i.test(filename)){const j=JSON.parse(text);items=Array.isArray(j)?j:j.sources;if(!Array.isArray(items))throw Error('Use a JSON array of sermon records or an object with a sources array.');}
    else if(/\.csv$/i.test(filename)){const [header,...rows]=parseCSV(text);if(!header)throw Error('This CSV is empty.');const map={title:'title',sermontitle:'title',campaigntitle:'title',subtitle:'subtitle',speaker:'speaker',pastor:'speaker',church:'church',scripture:'scripture',passage:'scripture',notes:'notes',transcript:'notes',body:'notes',url:'url',link:'url',date:'date',series:'series',bigidea:'bigIdea',practice:'practice',application:'practice',locator:'locator'};items=rows.map(r=>Object.fromEntries(header.map((h,i)=>[map[h.toLowerCase().replace(/[^a-z]/g,'')]||'ignored',r[i]])));}
    else {const lines=text.trim().split('\n'),first=lines[0]?.replace(/^#+\s*/,'').trim();items=[{title:first&&first.length<180?first:filename.replace(/\.[^.]+$/,''),notes:text}];}
    if(items.length>200)throw Error('Import up to 200 sermons at a time.');if(items.some(x=>String(x.notes||'').length>60000))throw Error('A sermon exceeds 60,000 characters. Split it into smaller messages before importing.');return items.map(x=>source({...x,id:id(),layer,permission:layer==='pastor'?'internal':'reference'})).filter(x=>x.title.trim());
  }
  function markdown(c) {
    const p=c.profile,ww=syncWeeks(c),cap=capacity(c),assets=descriptors(c),ss=selected(c);let out=`# ${c.title||'Campaign blueprint'}\n\n${c.subtitle}\n\nStatus: ${c.review.approved?'Pastoral review recorded; verify readiness checklist':'PROPOSED — working campaign'}\nPermission scope: INTERNAL CONCEPT until source and distribution review are complete.\n\n## Vision & church context\n\nChurch: ${p.church||'To assign'}\nPastor: ${p.pastor||'To assign'}\nAudience: ${p.audience}\nDuration: ${p.duration} days\nLaunch: ${p.launchDate||'Not scheduled'}\n\nTransformation goal: ${p.objective}\n\nLocal context: ${p.context}\nMission & values: ${p.mission}\nTheological convictions: ${p.theology}\nVoice: ${p.voice}\nScripture translation: ${p.translation}\n\nCatalytic experience: ${p.catalytic}\nChampions: ${p.champions}\nDistribution: ${p.distribution}\nStories: ${p.stories}\nMultiplication: ${p.multiplication}\nNext step: ${p.nextStep}\n\n## Scope & editions\n\n${components.map(x=>'- '+x.label+': '+({now:'Included now',later:'Later phase',off:'Not included'}[c.scope[x.id]])).join('\n')}\n\n## Source library\n\n${ss.map(s=>'### '+s.title+'\n'+s.subtitle+'\n\n'+layers[s.layer]+' · '+s.permission+'\nSpeaker: '+s.speaker+'\nChurch: '+s.church+'\nSource ID: '+(s.recordId||s.id)+'\nLink: '+s.url+'\nLocator: '+s.locator+'\nScripture: '+s.scripture+'\nBig idea: '+s.bigIdea+'\nPractice: '+s.practice).join('\n\n')}\n\n## Weekly blueprint\n\n`;
    out+=ww.map(w=>`### Week ${w.number}: ${w.title}\n\n${w.bigIdea}\n\nScripture: ${w.scripture}${w.scriptureSuggested?' (suggested; review required)':''}\nPractice: ${w.practice}\nGroup conversation: ${w.groupQuestion}\nFamily practice: ${w.familyPractice}\nSources: ${w.sourceIds.map(id=>c.sources.find(s=>s.id===id)?.title||'Source removed').join('; ')||'Editorial expansion — source needed'}\nReviewed: ${w.reviewed?'Yes':'No'}`).join('\n\n');
    out+='\n\n## Daily rhythm\n\n'+days(c).map(d=>`- Day ${d.number} · ${d.date||'Not scheduled'} · Week ${d.week} · ${d.kind}`).join('\n');
    out+='\n\n## Launch plan\n\n'+launchTasks(c).map(t=>`- [${t.done?'x':' '}] ${t.date||'Launch '+(t.offset<0?t.offset:'+'+t.offset)+' days'} · ${t.title} · ${t.owner||'Owner unassigned'}`).join('\n');
    out+=`\n\n## Capacity assumptions\n\nAttendance: ${p.attendance||'Not supplied'}\nParticipation target: ${p.participation}%\nPeople per group: ${p.groupSize}\nExisting groups: ${p.existingGroups}\nPrint buffer: ${p.printBuffer}%\nCalculated participants: ${cap.participants}\nGroups needed: ${cap.groups}\nAdditional hosts needed: ${cap.newHosts}\nPrinted copies: ${cap.copies}\nThese figures are planning calculations, not reported outcomes.\n\n## Outcomes recorded by your team\n\n${Object.entries(c.measures).map(([k,v])=>k+': '+(v||'Not recorded')).join('\n')}\n\n## Readiness\n\n${readiness(c).map(x=>'- ['+(x.done?'x':' ')+'] '+x.label).join('\n')}\n\nPastoral reviewer: ${c.review.pastor||'Not assigned'}\nReview date: ${c.review.date||'Not recorded'}\n\n## Resource drafts\n\n`;
    out+=assets.map(d=>{const a=c.assets[d.id];return '### '+d.label+'\n\nStatus: '+(a?.status||'Not drafted')+'\nOwner: '+(a?.owner||d.owner+' role — unassigned')+'\nReviewer: '+(a?.reviewer||'Unassigned')+'\n\n'+(a?.body||'Create this draft in the campaign workspace.');}).join('\n\n---\n\n');return out;
  }
  const icalEscape = v => String(v).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
  function calendar(c) {
    if(!date(c.profile.launchDate))throw Error('Add a launch date before downloading the calendar.');
    const events=launchTasks(c).map(t=>({id:t.id,date:t.date,title:t.title,description:(t.owner||t.role+' — owner unassigned')+'; '+(c.title||'Campaign')}));
    for(const w of syncWeeks(c))events.push({id:'week-'+w.number,date:date(c.profile.launchDate,(w.number-1)*7),title:'Week '+w.number+': '+w.title,description:w.bigIdea});
    return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//LifeTogether//Campaign Builder//EN','CALSCALE:GREGORIAN',...events.flatMap(e=>['BEGIN:VEVENT','UID:'+e.id+'-'+c.id+'@lifetogether.local','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART;VALUE=DATE:'+e.date.replace(/-/g,''),'DTEND;VALUE=DATE:'+date(e.date,1).replace(/-/g,''),'SUMMARY:'+icalEscape(e.title),'DESCRIPTION:'+icalEscape(e.description),'END:VEVENT']),'END:VCALENDAR'].map(line=>{let lines=[],part='';for(const ch of line){if(new TextEncoder().encode(part+ch).length>73){lines.push(part);part=' '+ch;}else part+=ch;}lines.push(part);return lines.join('\r\n');}).join('\r\n')+'\r\n';
  }
  function example() {const c=create({church:'Example church',goal:'community',objective:'build meaningful friendships, welcome someone new, and commit to an ongoing small group',context:'People attend regularly but many have not yet found a circle of trusted relationships.',nextStep:'Keep meeting with your group for the next six weeks and invite one more person.',catalytic:'A shared meal and an invitation to join a group after the launch gathering.',champions:'Pastor, groups coordinator, and volunteer hosts',attendance:250});c.title='Together on Purpose';c.subtitle='40 days of belonging, shared faith, and everyday hospitality';c.example=true;syncWeeks(c);return c;}
  return {schema,durations,layers,goals,components,phases,id,copy,clean,number,norm,safeURL,date,weekCount,create,source,denied,catalogLayer,fromRecord,searchCatalog,selected,teachingSources,extracted,syncWeeks,capacity,days,descriptors,draft,fingerprint,buildAssets,launchTasks,readiness,importCampaign,docxXML,parseCSV,importSources,markdown,calendar,example};
})();
if(typeof module!=='undefined')module.exports=LTCampaign;
